### ISSUE TITLE
System Crashes on Win7 (32-bit and 64-bit)

### ISSUE THREAD

**Issue by hdeoskar** [bitwiseworks/InJoy#11]
The driver crashes the system when IPSec connections are used for longer durations.

sdk version: 4.1
Platform Used: Win 7 (32-bit and 64-bit); Win-XP
Frequency of issue: More on Win7 and relatively less on WinXP

**Comment by SilvanScherrer** [comment]
This isssue should be fixed with the last SDK we sent to you
