### ISSUE TITLE
Traffic blocked from Client till Connection is created/aborted

### ISSUE THREAD

**Issue by hdeoskar** [bitwiseworks/InJoy#15]
1. Attempt tunnel creation from the client.
2. Ensure that the server takes time to respond OR does not respond.
3. Till the time the tunnel gets established OR user aborts the connection, other traffic expected to go out through the physical inerface also gets blocked.

Toolkit Version: 4.1
Client Platform: Win-XP

**Comment by SilvanScherrer** [comment]
The network interruption at driver installation is a windows
limitation, there is not solution for this. The workaround is to
install drivers at reboot.
