### ISSUE TITLE
Windows build system using kBuild

### ISSUE THREAD

**Issue by ydario** [bitwiseworks/InJoy#16]
Task for tracking changes to build system for Windows systems.

**Comment by ydario** [comment]
Commit della Revisione 8928 eseguito.

**Comment by ydario** [comment]
Adding         win\Makefile.kmk
Transmitting file data .
Committed revision 8930.

**Comment by ydario** [comment]
Add build of Windows 32bit and 64bit drivers and applications.
Commited revision 8932.

**Comment by ydario** [comment]
Convert line terminator to CRLF. Issue#16.
Committed revision 8937.

**Comment by ydario** [comment]
gateway uses windows subsystem. Issue#16.
Sending        trunk\gateway\Makefile.kmk
Transmitting file data .
Committed revision 8939.

**Comment by ydario** [comment]
Fix building of zip and exe installer packages. Issue#16.
Sending        Makefile.kmk
Sending        dw\win\dw.c
Sending        ijfw.files
Sending        install\sfxace\Makefile.kmk
Sending        install\uninst\Makefile.kmk
Transmitting file data .....
Committed revision 8940.

**Comment by ydario** [comment]
Make GUI applications to use windows subsystem. Issue#16.
Sending        Config.kmk
Sending        fgui\Makefile.kmk
Sending        gateway\Makefile.kmk
Sending        logview\Makefile.kmk
Transmitting file data ....
Committed revision 8941.

**Comment by ydario** [comment]
Build and package IPSec toolkit sdk for OS/2 and Windows 32bit/64bit. Issue#16.
Sending        trunk/Config.kmk
Sending        trunk/Makefile.kmk
Adding         trunk/sdk-packet/Makefile.kmk
Sending        trunk/sdk-packet/instdrv.bat
Sending        trunk/sdk-packet/ipapi-lnx.c
Adding         trunk/sdk-packet/ipapi.def
Sending        trunk/sdk-packet/ipapi.h
Adding         trunk/sdk-packet/testapp/Makefile.kmk
Sending        trunk/sdk-packet/testapp/testapp.c
Adding         trunk/sdk-packet/testapp2/Makefile.kmk
Sending        trunk/sdk-packet/testapp2/testapp2.c
Adding         trunk/sdk-packet/testapp3/Makefile.kmk
Sending        trunk/sdk-packet/testapp3/testapp3.c
Adding         trunk/sdk-packet/testapp4/Makefile.kmk
Sending        trunk/sdk-packet/testapp4/testapp4.c
Adding         trunk/sdk-packet/testapp5/Makefile.kmk
Sending        trunk/sdk-packet/testapp5/dialup.c
Sending        trunk/sdk-packet/testapp5/testapp.c
Adding         trunk/sdk-packet/testapp6/Makefile.kmk
Sending        trunk/sdk-packet/testapp6/emul41.h
Sending        trunk/sdk-packet/testapp6/testapp6.c
Sending        trunk/sdk-packet/uninstdrv.bat
Committed revision 8943.

**Comment by ydario** [comment]
Build and package IPSec toolkit sdk for OS/2 and Windows 32bit/64bit. Issue#16.
Sending        ijfw.files
Sending        sdk-packet\Makefile.kmk
Sending        sdk-packet\ipapi-win.def
Sending        sdk-packet\testapp5\Makefile.kmk
Sending        sdk-packet\testapp6\Makefile.kmk
Sending        sdk-packet\testapp6\testapp6.c
Transmitting file data ......
Committed revision 8944.

**Comment by ydario** [comment]
Build and package IPSec toolkit sdk for OS/2 and Windows 32bit/64bit. Issue#16.
Sending        fxauth\Makefile.kmk
Sending        ipsec\Makefile.kmk
Transmitting file data ..
Committed revision 8946.

**Comment by ydario** [comment]
Build and package IPSec toolkit sdk for OS/2 and Windows 32bit/64bit. Issue#16.
Sending        Config.kmk
Sending        Makefile.kmk
Sending        ijfw.files
Adding         sdk-packet\Makefile-SDK.kmk
Sending        sdk-packet\Makefile.kmk
Sending        sdk-packet\testapp\Makefile.kmk
Sending        sdk-packet\testapp2\Makefile.kmk
Sending        sdk-packet\testapp3\Makefile.kmk
Sending        sdk-packet\testapp4\Makefile.kmk
Sending        sdk-packet\testapp5\Makefile.kmk
Sending        sdk-packet\testapp6\Makefile.kmk
Transmitting file data ...........
Committed revision 8947.

**Comment by ydario** [comment]
Build and package IPSec toolkit sdk for OS/2 and Windows 32bit/64bit. Issue#16.
Sending        ijfw.files
Adding         sdk-packet\Config.kmk
Transmitting file data ..
Committed revision 8948.

**Comment by ydario** [comment]
Build and package IPSec toolkit sdk for OS/2 and Windows 32bit/64bit. Issue#16.
Sending        sdk-packet\Config.kmk
Sending        sdk-packet\Makefile.kmk
Transmitting file data ..
Committed revision 8949.

**Comment by ydario** [comment]
Build and package IPSec toolkit sdk for OS/2 and Windows 32bit/64bit. Issue#16.
Sending        sdk-packet\Makefile-SDK.kmk
Transmitting file data .
Committed revision 8950.

**Comment by ydario** [comment]
Add templates for binaries digital signing. Issue#16.
Sending        trunk\Config.kmk
Committed revision 8979.

**Comment by ydario** [comment]
Add of digital signatures for 32-bit and 64-bit drivers.
Removed old .inf/.cdf files and precompiled binaries. Issue#16.
Sending        ijfw.files
Sending        windrv\adapter\Makefile.kmk
Sending        windrv\adapter\RESOURCE.RC
Deleting       windrv\adapter\amd64
Deleting       windrv\adapter\disk
Adding         windrv\adapter\fx.inf
Sending        windrv\dod\Makefile.kmk
Sending        windrv\dod\RESOURCE.RC
Deleting       windrv\dod\amd64
Deleting       windrv\dod\disk
Adding         windrv\dod\fxdod.inf
Sending        wrap-win\Makefile.kmk
Deleting       wrap-win\amd64
Deleting       wrap-win\fxwrap.cdf
Sending        wrap-win\fxwrap.inf
Sending        wrap-win\fxwrap.rc
Sending        wrap-win\fxwrap_m.inf
Transmitting file data ...........
Committed revision 8980.

**Comment by ydario** [comment]
Add a signature removal tool. Issue#16.
Sending        ijfw.files
Sending        install\Makefile.kmk
Adding         install\unsigntool.cpp
Committed revision 8981.

**Comment by ydario** [comment]
Add digital signature to installer (needs to remove installer stub signature, otherwise signtool complaints with error 0x80070057). Issue#16.
Sending        Makefile.kmk
Committed revision 8982.

**Comment by ydario** [comment]
Convert LF to CRLF for windows batch files and shortcuts. Issue#16.
Sending        docs\firewall\win\bww.url
Sending        docs\firewall\win\deltrace.bat
Sending        docs\firewall\win\docs.url
Sending        docs\firewall\win\foldfire.bat
Sending        docs\firewall\win\homefire.url
Sending        docs\firewall\win\instfire.bat
Sending        docs\firewall\win\prchfire.url
Sending        docs\firewall\win\uninfire.bat
Transmitting file data ........
Committed revision 8983.

**Comment by ydario** [comment]
Disable binaries installation when signing code. Issue#16.
Sending        windrv\adapter\Makefile.kmk
Sending        windrv\dod\Makefile.kmk
Sending        wrap-win\Makefile.kmk
Transmitting file data ...
Committed revision 8984.

**Comment by ydario** [comment]
Add digital signature to fxinst executable.
Fix crash on debug output. Issue#16.
Sending        Config.kmk
Sending        windrv\2k-inst\Makefile.kmk
Sending        windrv\2k-inst\snetcfg.cpp
Transmitting file data ...
Committed revision 8985.

**Comment by ydario** [comment]
Do not stage unsigntool binary. Issue#16.
Sending        Makefile.kmk
Sending        install\Makefile.kmk
Transmitting file data ..
Committed revision 8986.

**Comment by ydario** [comment]
Install driver program improvement, adding getopt() parsing. Issue#16.
Adding         windrv\2k-inst\getopt
Adding         windrv\2k-inst\getopt\getopt.c
Adding         windrv\2k-inst\getopt\getopt.h
Adding         windrv\2k-inst\getopt\getopt1.c
Transmitting file data ...
Committed revision 8987.

**Comment by ydario** [comment]
Use new fxinst32/64 helpers for accessing drivers or registry. Issue#16.
Sending        docs\firewall\win\instfire.bat
Sending        docs\firewall\win\uninfire.bat
Sending        install\scripts\finished.cmd
Sending        install\scripts\page5.cmd
Transmitting file data ....
Committed revision 8989.

**Comment by ydario** [comment]
Fix fxwrap driver information file. Issue#16.
Sending        wrap-win\Makefile.kmk
Sending        wrap-win\fxwrap.inf
Transmitting file data ..
Committed revision 8990.

**Comment by ydario** [comment]
Strip comments from .inf files. Issue#16.
Sending        trunk\Config.kmk
Transmitting file data .
Committed revision 8992.

**Comment by ydario** [comment]
Allow separate installation of fx/fxdod and fxwrap drivers.
Always install all drivers. Issue#16.
Sending        install\scripts\finished.cmd
Sending        install\scripts\page5.cmd
Sending        install\scripts\page6.cmd
Sending        windrv\2k-inst\Makefile.kmk
Sending        windrv\2k-inst\fxinst.c
Sending        windrv\2k-inst\fxinst.h
Sending        windrv\2k-inst\install.c
Transmitting file data .......
Committed revision 8993.

**Comment by ydario** [comment]
Update of .inf files using newer templates.
Use SetupCopyOEMInf to force fxwrap_m.inf copy, since CopyINF directive is not honored on xp, probably the installer code is too old. Issue#16.
Sending        windrv\2k-inst\install.c
Sending        windrv\2k-inst\snetcfg.cpp
Sending        windrv\2k-inst\snetcfg.h
Sending        windrv\2k-inst\win32sup.cpp
Sending        windrv\adapter\fx.inf
Sending        windrv\dod\fxdod.inf
Sending        wrap-win\fxwrap.inf
Sending        wrap-win\fxwrap_m.inf
Transmitting file data ........
Committed revision 8994.

**Comment by ydario** [comment]
Fix build on 64-bit systems. Issue#16.
Trasmetto      trunk\Config.kmk
Trasmissione dati .
Commit della Revisione 8997 eseguito.

**Comment by ydario** [comment]
Fix SMP build. Issue#16.
Sending        windrv\2k-inst\Makefile.kmk
Transmitting file data .
Committed revision 8998.

**Comment by ydario** [comment]
Static linked regina rexx code does not allow RxFuncAdd, this is why the 64 bit installers were never used. Reverting to old scripting way. Issue#16.
Sending        install\scripts\finished.cmd
Sending        install\scripts\page5.cmd
Transmitting file data ..
Committed revision 8999.

**Comment by ydario** [comment]
Remove fxinst dll code and merge it back into executable, as it was before. Issue#16.
Sending        windrv\2k-inst\Makefile.kmk
Deleting       windrv\2k-inst\install64.rc
Sending        windrv\2k-inst\rexx_fxinst.c
Transmitting file data ..
Committed revision 9000.

**Comment by SilvanScherrer** [comment]
i consider this task done, as all builds with kbuild
