### ISSUE TITLE
Review Documentation

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/InJoy#24]
we need to review all documentation, as there is some old info in them.

**Comment by ydario** [comment]
Add version number and build type to desktop objects and readme text. Issue#24.
Sending        Config.kmk
Sending        Makefile.kmk
Sending        docs/firewall/Makefile.kmk
Sending        docs/firewall/os2/folder.cmd
Sending        docs/firewall/readme.os2
Sending        docs/firewall/readme.win
Sending        docs/firewall/win/foldfire.bat
Transmitting file data .......
Committed revision 9028.

**Comment by ydario** [comment]
Add version number and build type to desktop objects and readme text. Issue#24.
Sending        docs/firewall/Makefile.kmk
Sending        docs/firewall/os2/folder.cmd
Sending        docs/firewall/win/foldfire.bat
Committed revision 9030.

**Comment by ydario** [comment]
Add version number and build type to desktop objects and readme text. Issue#24.
Sending        win/foldfire.bat
Committed revision 9031.

**Comment by SilvanScherrer** [comment]
I consider this done since some month already.
