### ISSUE TITLE
Injoy 4.2 beta does not work on Windows 8

### ISSUE THREAD

**Issue by herwigb** [bitwiseworks/InJoy#26]
In an attempt to reproduce an issue reported by another user, Injoy 4.2 beta does not work on Windows 8. Installation seems to work normally (no error reports), however starting the the firewall server results in:
Error: Network interface is not operational. Retrying.

**Comment by herwigb** [comment]
![screenshot](https://f.cloud.github.com/assets/1766265/663506/288ec2a6-d76f-11e2-9257-c5b1285be19d.jpg)

**Comment by SilvanScherrer** [comment]
which Win8 version was it? Win8 Pro?

**Comment by SilvanScherrer** [comment]
probably the same as #25

**Comment by SilvanScherrer** [comment]
according to testers this issue is fixed
