### ISSUE TITLE
Build NDIS toolkit

### ISSUE THREAD

**Issue by ydario** [bitwiseworks/InJoy#27]
The current build system lacks the creation of NDIS toolkit.

NDIS toolkit is made of fxwrap drivers, driver installation scripts, ipapi and test applications (1 and 5).

A demo toolkit is also needed.

**Comment by ydario** [comment]
For demo kit, a new time bombed ipapi is built, name is ipapiD. Also test applications must be linked against Demo library, this requires duplication of code.

**Comment by ydario** [comment]
Build NDIS toolkit and demo code, issue#27.
Sending        Config.kmk
Sending        Makefile.kmk
Sending        sdk-packet\Makefile-SDK.kmk
Adding         sdk-packet\ipapi-demo.cc
Sending        sdk-packet\ipapi-win.c
Sending        sdk-packet\ipapi-win.def
Sending        sdk-packet\testapp\Makefile.kmk
Sending        sdk-packet\testapp5\Makefile.kmk
Transmitting file data ........
Committed revision 9038.

**Comment by ydario** [comment]
Current demo will expire on 31 Dec 2013.

**Comment by SilvanScherrer** [comment]
Yuri shouldn't we close this, as it's done?
