### ISSUE TITLE
Use standard/custom paths for config and log files

### ISSUE THREAD

**Issue by ecomstation** [bitwiseworks/InJoy#29]
https://svn.bitwiseworks.com/injoy/ticket/7

**Comment by ydario** [comment]
User can set a custom LOG directory using the %IJFW_LOGFILES% environment variable.
OS/2 defaults to %LOGFILES%/bww variable if defined.
Windows defaults to %APPDATA%/bww/ijfw variable if defined.
Otherwise local directory is used.

**Comment by ydario** [comment]
User can set a custom CONFIG directory using the %IJFW_CFGFILES% environment variable.
OS/2 defaults to %ETC%/bww variable if defined.
Windows defaults to %APPDATA%/bww/ijfw variable if defined.
Otherwise local directory is used.
