### ISSUE TITLE
Gui installer

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/InJoy#3]
The Gui installer should backup the config.sys and protocol.ini and eventually also send a message that it was changed.

**Comment by herwigb** [comment]
A totally superfluos comment

**Comment by AndiB-2** [comment]
Tested again and backup files are created. Most probably my fault didn't find the backup files the first time. 

But message with path\name of backup files would be fine as it is done by cli installer.

**Comment by SilvanScherrer** [comment]
done in the latest gui installer
