### ISSUE TITLE
Allow Remote GUI control of older versions

### ISSUE THREAD

**Issue by ydario** [bitwiseworks/InJoy#37]
The remote GUI can only control installations with matching major and minor version.
Since data flow did not change, we can allow controlling 4.1 and maybe even 4.0 installations.

**Comment by SilvanScherrer** [comment]
afaik there was never a 4.0 version. And from 3.x to 4.x the data flow changed.

**Comment by ydario** [comment]
Maybe 4.1 followed shortly after 4.0, but FX released a 4.0 set of binaries. I remember I did the update and then I left a copy of 4.0 into a different dir to connect to some customers.

**Comment by SilvanScherrer** [comment]
You are right. The 4.1 followed about 2 weeks after 4.0. I'd say its save to say that the dataflow for 4.x is all the same.

**Comment by ydario** [comment]
Issue#37: restore fgui protocol version.
Sending        src/fgui/gwremote.c
Sending        src/fgui/gwxp.c
Sending        src/gateway/remote.c
Sending        src/include/gwxpdata.h
Committed revision 9112.

**Comment by ydario** [comment]
Issue#37: restore fgui protocol version.
Sending        ijfw_4_2/fgui/gwremote.c
Sending        ijfw_4_2/fgui/gwxp.c
Sending        ijfw_4_2/gateway/remote.c
Sending        ijfw_4_2/include/gwxpdata.h
Committed revision 9113.

**Comment by ydario** [comment]
It is not possible to connect to 4.0 installations without breaking 4.1 installations.
Closing this ticket.
