### ISSUE TITLE
4.2 GA installer is unable to uninstall a previous version properly

### ISSUE THREAD

**Issue by herwigb** [bitwiseworks/InJoy#38]
On my testmachine I had a 4.2 beta installed - when I now tried to install the 4.2 GA 9101 build, it was unable to remove the old installation properly. The old dial-up driver seems to be still there and I was unable to get rid of it. Without that, a new installation is impossible.

**Comment by SilvanScherrer** [comment]
Did you try to uninstall the old beta first? This might be a problem now, as the dialup part changed completely.

**Comment by herwigb** [comment]
No. And I know this is quite likely the problem. However I'd assume that the same will apply in case someone installed a 4.1 some time in the past and now tries to install 4.2 - he will get stuck the same way...: 4.1 is gone and 4.2 refuses to install because of the old dial up driver...

**Comment by ydario** [comment]
Do you still have the beta build revision? so I will try to reproduce on a VM.

**Comment by herwigb** [comment]
I have the beta build and will try today to uninstall the dial up driver using that.
The beta build is the 9031b in your dropbox.

**Comment by SilvanScherrer** [comment]
@herwigb can this be closed?

**Comment by herwigb** [comment]
Yes.
