### ISSUE TITLE
Misleading 'fgui -?' output

### ISSUE THREAD

**Issue by AndiB-2** [bitwiseworks/InJoy#43]
'fgui -?' says ... [-i:<<> path to ini file<>>] but expects the ini file not the path only. Specifying the ini file with full path works.

f.i. 'fgui -i:p:\ijf4.2.2\MyIniFiles' leads to errors afterwards saying can not store ini.....
but 'fgui -i:p:\ijf4.2.2\MyIniFiles\fgui_Banzai.ini' works.

**Comment by SilvanScherrer** [comment]
ok wording is changed to [-i:<ini file (including path)>] for the next release.
thanks for sending the request.
