### ISSUE TITLE
DosRequestMutexSem call timed out

### ISSUE THREAD

**Issue by AndiB-2** [bitwiseworks/InJoy#47]
That's what I got today -
```
{20}[p:\injoyfirewall] gateway.exe
InJoy Firewall, Copyright (C) bww bitwise works GmbH
gateway version 4.2.2 (GA)
FXWRAP.SYS (DD) version 4.2 (0)

Licensed to [Andreas Buchinger]
Firewall interface [lan1] [10.0.0.202]
Internal Network 1: [10.0.2.0/255.255.255.0]
Internal Network 2: [192.168.1.0/255.255.255.0]
Internal Network 3: [172.16.0.0/255.31.0.0]
Fragmentation disabled
IPSec version [4.2]
Firewall version [4.2]
Firewall PC is [stealth]
GUI Server listen :port :3333

InJoy Firewall Ready!

Press 'T' to toggle packet tracing.
Press '5' for IPSec SA Table -- Press '6' for IPSec user table.
Press '7' for active TCP connections.
Press '8' for Firewall rule statistics -- Press '9' for NAT statistics.

Press 'H' to show this help again

Press 'SHIFT+Q' to stop InJoy Firewall ...


Firewall: Refreshing configuration
Firewall: Configuration refreshed!
16:47:37 ERROR.: DosRequestMutexSem call timed out - source: [E:/trees/injoy/ijf
w/branches/ijfw_4_2/gateway/eth_os2.c] - line: [75]
```

gateway.exe does behave strange on this system. Sometimes it seems to block the whole system. After minutes CTRL-ALT-DEL window show up finally an I could kill gateway.exe. I started it again and after a few minutes I got above error.

**Comment by AndiB-2** [comment]
I suspect this may be some power saving problem as the problem occurs after a while of running. I got a slightly different error now -
```
17:00:08 ERROR.: DosRequestMutexSem call timed out - source: [E:/trees/injoy/ijf
w/branches/ijfw_4_2/gateway/eth_os2.c] - line: [75]
Fatal: SIOSTATIF failed :-1
IP Address not configured, using 1.1.1.1 as a temporary address.
FW: new IP address :[1.1.1.1]
FW: new IP address :OK
FW: new IP address :[10.0.0.202]
FW: new IP address :OK
```

**Comment by ecomstation** [comment]
i've seen that i've this   DEVICE=C:\MPTN\PROTOCOL\FWIP.SYS   (could this create problems to injoy fw?)
i commented   BASEDEV=APM.ADD
let's see what happens

**Comment by ecomstation** [comment]
this morning i got:

errors.err:
Thu Feb  2 09:19:56 2017 - Killed by signal! (C0010003)

activity.log:

IP Address not configured, using 1.1.1.1 as a temporary address.
FW: new IP address :[1.1.1.1]
FW: new IP address :OK
Killed by signal! (C0010003)
Stopping I/O threads...
Stopping IPSec Plugin...
InJoy Firewall, Copyright (C) F/X Communications
gateway version 4.1 (2)
Fatal: Unable to open FXWRAP.SYS
Stopping Firewall Plugin...
Stopping IDENT support...
Shutdown complete - Exiting.


strange thing: Pluto.exe process was still running, only Gateway.exe crashed/exited
also in this moment i've seen an important numer of ip sockets

**Comment by AndiB-2** [comment]
More and more I think this issue is related to power management. I'm using Davids latest Intel NIC drivers on this system for both interfaces. 

Since weeks I'm using a script which pings every 3 seconds on any interface. This seems to cure most of my problems. But this system does have only very little load. And my ADSL connection is slow and flaky. So it's often not clear what causes the performance issues I have additionally - ADSL router or InjoyFirewall server.  So my tests results should be taken with care. 

Another problem on this system (and a second one) maybe Peter Moylans iniserve utility which sometimes hangs the WPS (probably caused by network issues). After not starting it automatically from startup folder some strange problems seems to be gone. Again, limited testing, much guessing :-(

**Comment by ecomstation** [comment]
this lan has 1 server and about 10 desktop, it's a small biz, desktops are all W10 so be sure that they make internet traffic allmost allways (meteo app, news app, app updates, Windows 10 updates, office updates etc.. is a clinic, so there is personell H24 one server H24 active and at least 2 or 3 PCs active H24 365 days per year), the server is a domain controller with active directory and communicate with other 2 DC via IPSEC Injoy VPN H24/365 days per year)
sayd so, it's allmost impossible that there is no traffic/work on that nic

how can the nic go into power saving mode?
i've disabled everything in the config.sys and 3 days ago even commented BASEDEV APM.ADD
what i should do more?
should i check settings in the bios of the PC?
the PC is an HP Pro desktop with that Realtek gigabit eth on mobo and an Intel Pro 1000 XT on the pci slot 
the intel PRO 1000 XT serve the internal nat LAN
while Injoy is binded on the realtek
realtek is a low cost brand, should i replace it with an intel pro100s?

the internet connection is a classic "ADSL2+" 12Mbit downstreaming 1Mbit upstreaming
with a failover connection on Hiperlan Ofdm 6Mbit/1Mbit
router is a Cisco 8xx (new generation) 

all processes on my firewalls are started with a rexx script launched by startup.cmd

**Comment by SilvanScherrer** [comment]
do you still see the DosRequestMutexSem issue with all updates in place?

**Comment by AndiB-2** [comment]
No. As written above the constant ping seems to cure the problem. No new NIC drivers installed since then nor changed anything else. 

Except I use this system now as my main internet gateway. It simply works.
