### ISSUE TITLE
Injoy FW 4.2.2 with public static ip on wan NIC exit when connection go down

### ISSUE THREAD

**Issue by ecomstation** [bitwiseworks/InJoy#53]
As in the subject, Injoy FW 4.2.2 exit automatically when there is an internet connection issue.

Wed Nov  1 09:27:52 2017 - tid#1: Killed by signal! (C0010003)
Wed Nov  1 12:03:53 2017 - tid#1: Killed by signal! (C0010003)
Wed Nov  1 12:35:44 2017 - tid#1: Killed by signal! (C0010003)
Wed Nov  1 12:56:38 2017 - tid#1: Killed by signal! (C0010003)
Wed Nov  1 13:56:15 2017 - tid#1: Killed by signal! (C0010003) 

WAN (extranet) NIC has a public static ip (of an 8 ip class)

wan NIC:   ifconfig lan0 80.86.x.y netmask 255.255.255.248 metric 0 mtu 1500

**Comment by SilvanScherrer** [comment]
what do you mean with exit? is gateway.exe ending? or do you see a crash?

**Comment by ecomstation** [comment]
gateway.exe (and pluto) just exit/terminate/end
without any crash

**Comment by SilvanScherrer** [comment]
can you reproduce that in a test env as well? As I plugged out the WAN cable for some minutes and nothing ended. After plugin it in all worked again.

**Comment by ecomstation** [comment]
as you can see from errors.err log maybe there was a sequence of "up and down" of the line
connection is a WADSL hyperlan2

**Comment by SilvanScherrer** [comment]
please try to reproduce it, as else we search a needle

**Comment by ecomstation** [comment]
firewall pc (wan nic public static ip) -> cisco 28xx router (public static ip) -> 2 kind of media ADSL2+ / WADSL Hyperlan2 OFDM failover

this is the network architecture
when connections have issues injoy exit/end/auto-terminate 

a question, this code: C0010003
what does it means for injoy application?

**Comment by SilvanScherrer** [comment]
is this still a case? As killed by signal means you issued a kill command

**Comment by ecomstation** [comment]
you can close this ticket, since as communicated to you before i found on that server (and fixed) my rexx fault daemon was doing this thing (killing the fw in moments of high bandwidht use or when internet connection was going down)

**Comment by SilvanScherrer** [comment]
I can't remember all mails :) That's the reason I prefer communicating through the tickets.
Thanks for reminding me.
