### ISSUE TITLE
injoy exit when internet connection have heavy load C0010003

### ISSUE THREAD

**Issue by ecomstation** [bitwiseworks/InJoy#58]
Dear sirs,

all my 4.2.2 injoy installations (and even previous versions) terminate automatically when there is some important load on the internet connection, this is not tollerable in 2018.

Exiting it completely terminate downloads, important OS updates, vpn tunnels, skype calls, remote desktop sessions etc.. breaking business productivity.

I've put on the servers a rexx fault daemon that restart injoy, but this is not a solution, this is a work-around.

I'm asking for a fix as soon as possible, or sadly i'll have to move to another product.

Tue Mar 13 21:47:35 2018 - tid#1: Killed by signal! (C0010003)                  
Tue Mar 13 22:39:01 2018 - tid#1: Killed by signal! (C0010003)                  
Tue Mar 13 23:11:50 2018 - tid#1: Killed by signal! (C0010003)                  
Wed Mar 14 00:11:55 2018 - tid#1: Killed by signal! (C0010003)                  
Wed Mar 14 14:37:52 2018 - tid#1: Killed by signal! (C0010003)                  
Wed Mar 14 19:31:20 2018 - tid#1: Killed by signal! (C0010003)                  
Wed Mar 14 22:18:31 2018 - tid#1: Killed by signal! (C0010003)

thanks

massimo

**Comment by SilvanScherrer** [comment]
According to the reporter his fault daemon does/did a sync -kill on some occasions. So it's not a injoy issue, so we close it.
