### ISSUE TITLE
datarate performances drop with injoy fw (4.2.2) running

### ISSUE THREAD

**Issue by ecomstation** [bitwiseworks/InJoy#59]
Hi,

tests done using NETIO 1.3.3 on Supermicro Intel Xeon 4 Cores, 4GB ram, eCS 2.1 with Injoy FW 4.2.2

without: Injoy FW 4.2.2 (i mean with gateway.exe closed)

NETIO - Network Throughput Benchmark, Version 1.33
(C) 1997-2012 Kai Uwe Rommel
(c) 2016 David Azarewicz <david@88watts.net>

Press ESC to exit.
TCP server listening.
TCP connection established ...
Receiving from client, packet size 1k ... 65.06 MByte/s
Sending to client, packet size 1k ... 72.99 MByte/s
Receiving from client, packet size 2k ... 75.64 MByte/s
Sending to client, packet size 2k ... 77.17 MByte/s
Receiving from client, packet size 4k ... 77.81 MByte/s
Sending to client, packet size 4k ... 76.12 MByte/s
Receiving from client, packet size 8k ... 60.80 MByte/s
Sending to client, packet size 8k ... 70.06 MByte/s
Receiving from client, packet size 16k ... 68.72 MByte/s
Sending to client, packet size 16k ... 72.19 MByte/s
Receiving from client, packet size 32k ... 69.05 MByte/s
Sending to client, packet size 32k ... 65.26 MByte/s
Done.
TCP server listening.

with injoy FW 4.2.2

NETIO - Network Throughput Benchmark, Version 1.33
(C) 1997-2012 Kai Uwe Rommel
(c) 2016 David Azarewicz <david@88watts.net>

Press ESC to exit.
TCP server listening.
TCP connection established ...
Receiving from client, packet size 1k ... 3919.24 KByte/s
Sending to client, packet size 1k ... 25.34 MByte/s
Receiving from client, packet size 2k ... 8966.54 KByte/s
Sending to client, packet size 2k ... 13.06 MByte/s
Receiving from client, packet size 4k ... 6178.78 KByte/s
Sending to client, packet size 4k ... 16.99 MByte/s
Receiving from client, packet size 8k ... 3999.51 KByte/s
Sending to client, packet size 8k ... 18.81 MByte/s
Receiving from client, packet size 16k ... 5702.64 KByte/s
Sending to client, packet size 16k ... 18.60 MByte/s
Receiving from client, packet size 32k ... 2866.60 KByte/s
Sending to client, packet size 32k ... 27.93 MByte/s
Done.
TCP server listening.

**Comment by SilvanScherrer** [comment]
this is being worked on right now

**Comment by SilvanScherrer** [comment]
I close this in favour of #66
