### ISSUE TITLE
Injoy 4.2.2 GA trapD on ring0 

### ISSUE THREAD

**Issue by ecomstation** [bitwiseworks/InJoy#60]
Hi all,

since Yesterday i'm getting ring0 trap D on module FXWRAP (4.2.2 ga) nic Intel pro 1000 xt PCI-X
OS: eCS 2.1 ga
hw: Supermicro MOBO PDSME+ Intel Xeon 4 cores + 4GigaBytes ram

![wp_20181210_00_44_45_rich_](https://user-images.githubusercontent.com/2589993/49723723-d3cc1b00-fc67-11e8-9822-ea5f2dc6e313.jpg)

**Comment by lerdmann** [comment]
I had a look at this but since I have a newer kernel (I am using 14.106_SMP instead of 14.105_SMP) and since I use a newer build of FXWRAP.SYS than the 4.2.2 GA I can only speculate:
I think the trap happens when FXWRAP.SYS tries to copy an ethernet frame to the buffer provided by GATEWAY.EXE (for subsequent filtering).
I had a look in the code regarding this matter but everything appears to work correctly. The only thing that COULD go wrong is if GATEWAY.EXE allocates a buffer of a too small size but reports a BIGGER size to FXWRAP.SYS. That would then potentially lead to an overflow on copying the data to the provided buffer.
If what I think is true, we would need to have a look at GATEWAY.EXE. I'll keep that in the back of my head.

**Comment by ecomstation** [comment]
after upgrading to fxwrap beta 17/11/2018 144.036 bytes build, the server do not trap anymore at ring0
but starting gateway.exe i get allmost no TCP/IP communications, just ping works

i also get exceptQ crash/dump of gateway.exe (the original 4.2.2 ga build dated 26/06/14)
 
______________________________________________________________________

 Exception Report - created 2018/12/10 22:23:20
______________________________________________________________________

 InJoy Firewall 4.2.2 GA

 OS2/eCS Version:  2.45
 # of Processors:  4
 Physical Memory:  3582 mb
 Virt Addr Limit:  3072 mb
 Exceptq Version:  7.11.4-shl (Mar  6 2017)

______________________________________________________________________

 Exception C0000005 - Access Violation
______________________________________________________________________

 Process:  D:\FIREWALL3\GATEWAY.EXE (06/26/2014 16:12:29 73,409)
 PID:      52 (82)
 TID:      0E (14)
 Priority: 20A

 Filename: D:\FIREWALL3\FXUTIL.DLL (06/26/2014 16:12:28 19,444)
 Address:  005B:1E080130 (0001:00000130)
 Cause:    Attempted to read from 00000000
           (not a valid address)

______________________________________________________________________

 Failing Instruction
______________________________________________________________________

 1E080126  MOV   EDX, EBP         (89ea)
 1E080128  MOVZX EAX, [ESI+0x10]  (0fb746 10)
 1E08012C  CMP   EAX, EBX         (39d8)
 1E08012E  JLE   0x1e08017c       (7e 4c)
 1E080130 >MOV   EBP, [EDX]       (8b2a)
 1E080132  TEST  EDI, EDI         (85ff)
 1E080134  JZ    0x1e080110       (74 da)
 1E080136  MOV   EAX, [ESI+0x44]  (8b46 44)

______________________________________________________________________

 Registers
______________________________________________________________________

 EAX : 00000000   EBX  : 00000000   ECX : 00B8FC02   EDX  : 00000000
 ESI : 00564FE0   EDI  : 00000000
 ESP : 02637B5C   EBP  : 02637BBC   EIP : 1E080130   EFLG : 00010202
 CS  : 005B       CSLIM: FFFFFFFF   SS  : 0053       SSLIM: FFFFFFFF

 EAX : not a valid address
 EBX : not a valid address
 ECX : read/write memory allocated by LIBC066
 EDX : not a valid address
 ESI : read/write memory allocated by LIBC066
 EDI : not a valid address

______________________________________________________________________

 Stack Info for Thread 0E
______________________________________________________________________

   Size       Base        ESP         Max         Top
 00008000   02638000 -> 02637B5C -> 02636000 -> 02630000

______________________________________________________________________

 Call Stack
______________________________________________________________________

   EBP     Address    Module     Obj:Offset    Nearest Public Symbol
 --------  ---------  --------  -------------  -----------------------
 Trap  ->  1E080130   FXUTIL    0001:00000130 


______________________________________________________________________

 Labels on the Stack
______________________________________________________________________

   ESP     Address    Module     Obj:Offset    Nearest Public Symbol
 --------  ---------  --------  -------------  -----------------------
 02637B5C  000100B2   GATEWAY   0001:000000B2 
 02637B68  1E0839BC   FXUTIL    0001:000039BC 
 02637B6C  000100B1   GATEWAY   0001:000000B1 
 02637B74  1E038CF0   FIREWALL  0001:00018CF0 
 02637B7C  000100AF   GATEWAY   0001:000000AF 
 02637B98  1E039A52   FIREWALL  0001:00019A52 
 02637BA4  1E038CF0   FIREWALL  0001:00018CF0 
 02637BB8  1F15AEB4   LIBC066   0001:0000AEB4  between _um_lump_alloc + 3CC and __libc_fhInit - 5EC
 02637BE8  1E039B38   FIREWALL  0001:00019B38 
 02637C18  1F1AE5E5   LIBC066   0001:0005E5E5  between _std_stat + 25 and _std_statfs - 5B
 02637C68  1F158763   LIBC066   0001:00008763  between DosCreateEventSemEx + 23 and __libc_dosexAlloc - 8D
 02637C88  1E025976   FIREWALL  0001:00005976 
 02637CA8  1E025C07   FIREWALL  0001:00005C07 
 02637CAC  0001005E   GATEWAY   0001:0000005E 
 02637CB4  1E0299F4   FIREWALL  0001:000099F4 
 02637D28  00022FEC   GATEWAY   0001:00012FEC 
 02637D38  000228AE   GATEWAY   0001:000128AE 
 02637D68  00023267   GATEWAY   0001:00013267 
 02637D88  0002335A   GATEWAY   0001:0001335A 
 02637D98  00010000   GATEWAY   0001:00000000 
 02637DB8  000104B9   GATEWAY   0001:000004B9 
 02637DC4  000103E9   GATEWAY   0001:000003E9 
 02637E08  00010F73   GATEWAY   0001:00000F73 
 02637E48  000111C0   GATEWAY   0001:000011C0 
 02637E98  00028304   GATEWAY   0001:00018304 
 02637F08  00011353   GATEWAY   0001:00001353 
 02637F48  00024130   GATEWAY   0001:00014130 
 02637F88  1E0836B1   FXUTIL    0001:000036B1 
 02637F98  1F180568   LIBC066   0001:00030568  between __libc_LogInit + F4 and __libc_LogGroupInit - 738
 02637FA8  000180F8   GATEWAY   0001:000080F8 
 02637FB8  1F18A6D3   LIBC066   0001:0003A6D3  between _endthread + 1AF and _chdir2 - 3B6D
 02637FD8  1F196E50   LIBC066   0001:00046E50  between _libc_Back_exceptionHandler + 140 and _libc_thunk1 - 260
 02637FF8  1FFECE38   DOSCALL1  0004:0000CE38  DOS32R3EXITADDR

______________________________________________________________________

 Stack Contents from ESP-10C to Stack Base  (ESP = 02637B5C)
______________________________________________________________________

 --addr--   --------------dwords---------------   -----chars------
 02637A50 : 00000000 33885395 00000000 00000000 : .....S.3........
 02637A60 : 00000052 00000000 00000000 00000000 : R...............
 02637A70 : 00000000 0000003E 00000000 00000000 : ....>...........
 02637A80 : 00000000 00000000 00000000 00000000 : ................
 02637A90 : 00000000 00000000 00000000 00000000 : ................
 02637AA0 : 0000150B 00000053 00000053 00000000 : ....S...S.......
 02637AB0 : 00564FE0 00000000 00000000 00B8FC02 : .OV.............
 02637AC0 : 00000000 02637BBC 1E080130 0000005B : .....{c.0...[...
 02637AD0 : 00010202 02637B5C 00000053 000100B5 : ....\{c.S.......
 02637AE0 : FFFFFFFF 00000000 00000001 00000000 : ................
 02637AF0 : 00000000 02637B14 1E083B89 000100B5 : .....{c..;......
 02637B00 : FFFFFFFF 02637C14 1F1984BC 02637BDC : .....|c......{c.
 02637B10 : 00000000 02637B54 1E083BC0 000100B2 : ....T{c..;......
 02637B20 : FFFFFFFF 00000000 00000001 00000000 : ................
 02637B30 : 02637BAC 02637B54 1E083C25 000100B2 : .{c.T{c.%<......
 02637B40 : FFFFFFFF 00000014 0000000F 00000001 : ................
 02637B50 : 00B8FDB3 02637BBC 1E0800F8 000100B2 : .....{c.........
 02637B60 : FFFFFFFF 00000041 1E0839BC 000100B1 : ....A....9......
 02637B70 : 00000000 1E038CF0 02637BC0 000100AF : .........{c.....
 02637B80 : FFFFFFFF 00000000 0000000F 00000001 : ................
 02637B90 : 00B8FDB3 02637BBC 1E039A52 00564FE0 : .....{c.R....OV.
 02637BA0 : 00000000 1E038CF0 02637BC0 00000029 : .........{c.)...
 02637BB0 : 004F0000 000000F3 1F15AEB4 00000000 : ..O.............
 02637BC0 : 00000001 02637C0C 00000001 02637C2C : .....|c.....,|c.
 02637BD0 : 02637C2C 02637BF4 0000000F 02637CE3 : ,|c..{c......|c.
 02637BE0 : 00B8FDB3 07305650 1E039B38 02637C0C : ....PV0.8....|c.
 02637BF0 : 00000001 00000000 02637CE3 00000029 : .........|c.)...
 02637C00 : 00000000 02637C34 02637C94 0000000A : ....4|c..|c.....
 02637C10 : 02637C2C 02637C84 1F1AE5E5 00000000 : ,|c..|c.........
 02637C20 : 02637C2C 02637CA4 004F0000 06000044 : ,|c..|c...O.D...
 02637C30 : 00B8FCFC 00B8FCF1 00000000 7FFFFFF4 : ................
 02637C40 : FFFFFFFF 00001182 7FFFFFFF 00000000 : ................
 02637C50 : FFFFFFFF 00000070 00000000 00000000 : ....p...........
 02637C60 : 00000401 00000000 1F158763 004F0000 : ........c.....O.
 02637C70 : 00000001 73345650 1BC00050 0000000F : ....PV4sP.......
 02637C80 : 73345650 07305650 1E025976 73345650 : PV4sPV0.vY..PV4s
 02637C90 : 00000000 02637CE3 00000029 00000000 : .....|c.).......
 02637CA0 : 00000007 02000008 1E025C07 0001005E : .........\..^...
 02637CB0 : 00000000 1E0299F4 00B8FCC0 00B7FAEE : ................
 02637CC0 : 73345650 00B72FD7 004F4C60 00B7FAEE : PV4s./..`LO.....
 02637CD0 : 00000000 00B7FB02 00000000 00000000 : ................
 02637CE0 : 00000000 00000030 00000001 00000000 : ....0...........
 02637CF0 : 00000000 02000008 00000000 00000000 : ................
 02637D00 : 00000000 00000000 00000000 00000000 : ................
 02637D10 : 00000000 00000000 00B7FAEE 02637E74 : ............t~c.
 02637D20 : 73341127 02000008 00022FEC 00B7FAEE : '.4s...../......
 02637D30 : 00000001 02000008 000228AE 00000008 : .........(......
 02637D40 : 00B7FB02 73345650 06000001 04000008 : ....PV4s........
 02637D50 : 50563007 001C7D06 02637E74 00B7FAEE : .0VP.}..t~c.....
 02637D60 : 02637ECA 00B7FAEE 00023267 00B7FAEE : .~c.....g2......
 02637D70 : 02637E74 02637E74 02637E74 00B7FAEE : t~c.t~c.t~c.....
 02637D80 : 02637E74 00B7FAEE 0002335A 00B7FAEE : t~c.....Z3......
 02637D90 : 02637E74 00000005 00010000 00000000 : t~c.............
 02637DA0 : 000001C1 02637E74 02637E74 00B7FAEE : ....t~c.t~c.....
 02637DB0 : 02637E74 00B7FAEE 000104B9 00B7FAEE : t~c.............
 02637DC0 : 02637E74 000103E9 0000000F 00000005 : t~c.............
 02637DD0 : 02637DF8 02637DF4 00000000 00000000 : .}c..}c.........
 02637DE0 : 00000000 00000000 00000032 00000000 : ........2.......
 02637DF0 : 00000000 00000000 02637E74 0000000F : ........t~c.....
 02637E00 : 02637E34 0000003E 00010F73 02637E34 : 4~c.>...s...4~c.
 02637E10 : 00B7FAE0 02637E74 00000000 00000000 : ....t~c.........
 02637E20 : 00000000 00000000 00000000 00000000 : ................
 02637E30 : 00000000 0000003E 00000000 02637E74 : ....>.......t~c.
 02637E40 : 00000001 02637EEC 000111C0 00B7FAE0 : .....~c.........
 02637E50 : 0000003E 02637E74 00000000 00000000 : >...t~c.........
 02637E60 : 00000000 00000000 00B7FAD8 00000000 : ................
 02637E70 : 004F0000 00000000 00000000 00000000 : ..O.............
 02637E80 : 00000000 00000000 73345650 00000000 : ........PV4s....
 02637E90 : 00000001 00000000 00028304 00000001 : ................
 02637EA0 : 00000008 00000000 00000000 00000000 : ................
 02637EB0 : 00000030 00000000 00000005 53FE71C4 : 0............q.S
 02637EC0 : 02007673 418699B3 00000008 00000000 : sv.....A........
 02637ED0 : 00000000 00000000 00000000 00000000 : ................
 02637EE0 : 00000000 00000000 00000000 004F013C : ............<.O.
 02637EF0 : 004F0000 02637F24 0000003E 00B7FAE0 : ..O.$.c.>.......
 02637F00 : 02637F68 0000000F 00011353 00B7FAE0 : h.c.....S.......
 02637F10 : 0000003E 00000005 00000000 00000000 : >...............
 02637F20 : 00000000 00000001 00B7FAE0 000005EA : ................
 02637F30 : 02637F68 02637F40 00000000 00000005 : h.c.@.c.........
 02637F40 : 00B7FAE0 00000005 00024130 0000003E : ........0A..>...
 02637F50 : 00B7FAE0 00000005 00000002 00000000 : ................
 02637F60 : 00000000 00000000 0000003E 00000000 : ........>.......
 02637F70 : 00000000 00000000 00B63518 02637FA4 : .........5....c.
 02637F80 : 00000000 02637FB4 1E0836B1 00000005 : ......c..6......
 02637F90 : 0000001D 02637FB4 1F180568 02637FD4 : ......c.h.....c.
 02637FA0 : 00000000 02637FD4 000180F8 2003C8E0 : ......c........ 
 02637FB0 : 02637FD4 02637FF4 1F18A6D3 00B63518 : ..c...c......5..
 02637FC0 : 00000000 00000000 00000000 00000000 : ................
 02637FD0 : 00000000 FFFFFFFF 1F196E50 00000000 : ........Pn......
 02637FE0 : 00000000 00000000 00000000 00000000 : ................

______________________________________________________________________

 Memory addressed by ECX (00B8FC02) for 256 bytes
______________________________________________________________________

 --addr--   -----dwords------   ---------bytes---------   -chars--
 00B8FC02 : 00000000 00000000 : 00 00 00 00 00 00 00 00 : ........
 00B8FCAA : 21 lines not printed duplicate the line above
 00B8FCB2 : 01D00000 00F30001 : 00 00 D0 01 01 00 F3 00 : ........
 00B8FCBA : 01510000 5650004F : 00 00 51 01 4F 00 50 56 : ..Q.O.PV
 00B8FCC2 : 56507334 30380730 : 34 73 50 56 30 07 38 30 : 4sPV0.80
 00B8FCCA : 2E36382E 312E3235 : 2E 38 36 2E 35 32 2E 31 : .86.52.1
 00B8FCD2 : 00003531 00000000 : 31 35 00 00 00 00 00 00 : 15......
 00B8FCDA : 00000000 00000000 : 00 00 00 00 00 00 00 00 : ........
 00B8FCE2 : 00000000 00000000 : 00 00 00 00 00 00 00 00 : ........
 00B8FCEA : 00000000 38000000 : 00 00 00 00 00 00 00 38 : .......8
 00B8FCF2 : 36382E30 2E38342E : 30 2E 38 36 2E 34 38 2E : 0.86.48.

______________________________________________________________________

 Memory addressed by ESI (00564FE0) for 256 bytes
______________________________________________________________________

 --addr--   -----dwords------   ---------bytes---------   -chars--
 00564FE0 : 00B8FDC0 00B8FDC0 : C0 FD B8 00 C0 FD B8 00 : ........
 00564FE8 : 000100B2 000100B3 : B2 00 01 00 B3 00 01 00 : ........
 00564FF0 : 676E0001 00000078 : 01 00 6E 67 78 00 00 00 : ..ngx...
 00564FF8 : 62206F74 65722065 : 74 6F 20 62 65 20 72 65 : to be re
 00565000 : 766C6F73 00006465 : 73 6F 6C 76 65 64 00 00 : solved..
 00565008 : 00000000 00000000 : 00 00 00 00 00 00 00 00 : ........
 00565010 : 00000000 0000BF54 : 00 00 00 00 54 BF 00 00 : ....T...
 00565018 : 00000914 004F0150 : 14 09 00 00 50 01 4F 00 : ....P.O.
 00565020 : 65660000 000100B2 : 00 00 66 65 B2 00 01 00 : ..fe....
 00565028 : 000100B3 0074696D : B3 00 01 00 6D 69 74 00 : ....mit.
 00565030 : 00000000 0000004C : 00 00 00 00 4C 00 00 00 : ....L...
 00565038 : 0000004C 004F0151 : 4C 00 00 00 51 01 4F 00 : L...Q.O.
 00565040 : 00B697A0 00B69920 : A0 97 B6 00 20 99 B6 00 : .... ...
 00565048 : 000100B6 000100B7 : B6 00 01 00 B7 00 01 00 : ........
 00565050 : 676E0005 00000140 : 05 00 6E 67 40 01 00 00 : ..ng@...
 00565058 : 61746164 65736162 : 64 61 74 61 62 61 73 65 : database
 00565060 : 79656B20 00000073 : 20 6B 65 79 73 00 00 00 :  keys...
 00565068 : 00000000 00000000 : 00 00 00 00 00 00 00 00 : ........
 00565070 : 00000000 00000034 : 00 00 00 00 34 00 00 00 : ....4...
 00565078 : 000000D4 004F0150 : D4 00 00 00 50 01 4F 00 : ....P.O.
 00565080 : 00000000 000100B6 : 00 00 00 00 B6 00 01 00 : ........
 00565088 : 000100B7 00000000 : B7 00 01 00 00 00 00 00 : ........
 00565090 : 00000000 0000004C : 00 00 00 00 4C 00 00 00 : ....L...
 00565098 : 0000002C 004F0151 : 2C 00 00 00 51 01 4F 00 : ,...Q.O.
 005650A0 : 656C7552 6D614E2D : 52 75 6C 65 2D 4E 61 6D : Rule-Nam
 005650A8 : 00560065 6F636E49 : 65 00 56 00 49 6E 63 6F : e.V.Inco
 005650B0 : 676E696D 00000034 : 6D 69 6E 67 34 00 00 00 : ming4...
 005650B8 : 00000094 004F0150 : 94 00 00 00 50 01 4F 00 : ....P.O.
 005650C0 : 00000001 00000000 : 01 00 00 00 00 00 00 00 : ........
 005650C8 : 00000000 00000000 : 00 00 00 00 00 00 00 00 : ........
 005650D0 : 00000000 0000002C : 00 00 00 00 2C 00 00 00 : ....,...
 005650D8 : 0000002C 004F0151 : 2C 00 00 00 51 01 4F 00 : ,...Q.O.

______________________________________________________________________

 DLLs accessible from this process
______________________________________________________________________

 PMCTLS    11/05/2009 23:36:18     645,926  C:\OS2\DLL\PMCTLS.DLL
 PMMERGE   04/10/2007 18:26:01   1,270,275  C:\OS2\DLL\PMMERGE.DLL
 PMGPI     10/16/2001 13:31:09     248,446  C:\OS2\DLL\PMGPI.DLL
 SEAMLESS  10/16/2001 22:03:14      49,167  C:\OS2\DLL\SEAMLESS.DLL
 DISTORM   11/12/2012 06:43:02      57,491  C:\UTIL\LIB\DISTORM.DLL
 IPFORMAT  06/26/2014 16:12:29      11,498  D:\FIREWALL3\IPFORMAT.DLL
 FIREWALL  06/26/2014 16:12:29     109,423  D:\FIREWALL3\FIREWALL.DLL
 GENERATE  06/26/2014 16:12:29      58,521  D:\FIREWALL3\GENERATE.DLL
 FXMASQ    06/26/2014 16:12:29      13,371  D:\FIREWALL3\FXMASQ.DLL
 IPFRAG    06/26/2014 16:12:29       4,928  D:\FIREWALL3\IPFRAG.DLL
 FXUTIL    06/26/2014 16:12:28      19,444  D:\FIREWALL3\FXUTIL.DLL
 KLIBCCFG  03/27/2007 11:46:08     162,927  C:\OS2\DLL\KLIBCCFG.DLL
 GCC1      02/01/2015 20:08:28      26,491  C:\UTIL\LIB\GCC1.DLL
 LIBC066   01/19/2018 17:10:13   1,361,663  C:\UTIL\LIB\LIBC066.DLL
 EXCEPTQ   03/07/2017 01:50:07      72,249  C:\UTIL\LIB\EXCEPTQ.DLL
 TCPIP32   08/16/2011 06:01:00      87,504  C:\MPTN\DLL\TCPIP32.DLL
 VBE2GRAD  05/16/2015 08:43:13      63,275  C:\OS2\DLL\VBE2GRAD.DLL
 PANOGREX  11/13/2014 13:44:16       2,032  C:\OS2\DLL\PANOGREX.DLL
 VMAN      03/22/2006 14:20:26      67,993  C:\OS2\DLL\VMAN.DLL
 GRE2VMAN  10/25/2007 16:54:19      21,325  C:\OS2\DLL\GRE2VMAN.DLL
 TRUETYPE  09/14/2001 15:42:00     128,567  C:\OS2\DLL\TRUETYPE.DLL
 PMUNIF    10/16/2001 14:59:29      43,823  C:\OS2\DLL\PMUNIF.DLL
 PMATM     09/14/2001 15:41:26     224,343  C:\OS2\DLL\PMATM.DLL
 DISPLAY   03/22/2006 08:54:14      44,198  C:\OS2\DLL\DISPLAY.DLL
 LOCALE    09/04/2002 17:31:00     108,353  C:\OS2\DLL\LOCALE.DLL
 SOMIR     06/30/1999 16:34:07      87,628  C:\OS2\DLL\SOMIR.DLL
 SOMTC     06/30/1999 16:34:12      30,484  C:\OS2\DLL\SOMTC.DLL
 IBMHMGR   12/14/2014 19:30:16     250,171  C:\OS2\DLL\IBMHMGR.DLL
 BDCALL32  09/14/2001 15:16:03      33,519  C:\OS2\DLL\BDCALL32.DLL
 PMBIDI    09/14/2001 15:17:06      13,611  C:\OS2\DLL\PMBIDI.DLL
 HELPMGR   08/17/2005 11:44:01      50,132  C:\OS2\DLL\HELPMGR.DLL
 PMEX      04/13/2011 09:31:25      13,114  C:\OS2\DLL\PMEX.DLL
 BDWPCLS   07/16/2003 02:35:00      24,832  C:\OS2\DLL\BDWPCLS.DLL
 SOMU      06/30/1999 16:34:12      81,044  C:\OS2\DLL\SOMU.DLL
 SOM       06/30/1999 16:33:02      92,009  C:\OS2\DLL\SOM.DLL
 LIBUNI    09/04/2002 19:34:00      80,766  C:\OS2\DLL\LIBUNI.DLL
 IMP       09/06/2000 12:45:08       6,681  C:\OS2\DLL\IMP.DLL
 SPL1B     07/15/2003 18:47:00       7,125  C:\OS2\DLL\SPL1B.DLL
 PMSPL     07/15/2003 18:47:00     280,283  C:\OS2\DLL\PMSPL.DLL
 PMSHLTKT  09/06/2000 12:45:10      44,232  C:\OS2\DLL\PMSHLTKT.DLL
 UCONV     09/04/2002 19:30:00      23,331  C:\OS2\DLL\UCONV.DLL
 SOFTDRAW  07/16/2003 10:21:00     416,735  C:\OS2\DLL\SOFTDRAW.DLL
 PMVIOP    07/16/2003 10:53:00      68,960  C:\OS2\DLL\PMVIOP.DLL
 PMWP      11/05/2009 23:34:07   1,235,735  C:\OS2\DLL\PMWP.DLL
 FFST      03/08/2002 18:23:00      11,425  C:\OS2\DLL\FFST.DLL
 DOSCALL1  11/24/2011 03:24:00     132,401  C:\OS2\DLL\DOSCALL1.DLL

______________________________________________________________________

 End of Exception Report - report took 203 ms to generate
______________________________________________________________________

**Comment by lerdmann** [comment]
1) Do you have up-to-date LIBC and LIBCX packages ? Please update to the latest version.
2) It's a good idea to clear the ARP cache and also the routing table and reset the default route once you restarted GATEWAY.

**Comment by ecomstation** [comment]
26/10/14 20:17         48.179    124 a---  libc06.dll
26/10/14 20:17         48.179    124 a---  libc061.dll
26/10/14 20:17        157.161    124 a---  libc062.dll
26/10/14 20:17        157.161    124 a---  libc063.dll
26/10/14 20:17        157.213    124 a---  libc064.dll
26/10/14 20:17        157.213    124 a---  libc065.dll
19/01/18 17:10      1.361.663    124 a---  libc066.dll
17/04/18  1:29         40.345    124 a---  libcx0.dll

i've seen that there are new builds:

libcx0.dll      40.731 11/09/18
libc066.dll     1.329K 05/06/18

updated them rebooted the server
injoy firewall still don't work properly

in a telnet session (i can login, but) is sufficient that i write: 

dir

to have no answer from the server…
(of course until from the console keyboard i kill gateway process)

of course all protocols/services do not answer (like pop3, http, ftp, etc.)

**Comment by lerdmann** [comment]
It's not my job to find out if these are most recent. Do your homework.

**Comment by ecomstation** [comment]
i've reinstalled the firewall directory from 422GA (but still using 17/10/2018 fxwrap.sys)

the firewall now works, BUT if i turn OFF "Dynamic firewall features" the issue show again

or the same if i turn ON one or both of these include rules:

#include <firewall/url_filter.cnf>
#include <firewall/spam.cnf>

**Comment by lerdmann** [comment]
Exactly what issue shows again ?
A Ring-0 trap in FXWRAP.SYS or a Ring-3 trap somewhere in FXUTIL.DLL or the inability to ping or otherwise remotely connect to the problematic machine in question ?

**Comment by ecomstation** [comment]
the 3rd situation, i can't neither ping the server from my office lan
no protocol works anymore pop, smtp, http, ftp etc.. etc.. 
it's like all get closed/filtered/banned by the firewall

**Comment by lerdmann** [comment]
Let's put this all together:
1) you are using GATEWAY.EXE 4.2.2 GA in all cases
2) if you use FXWRAP.SYS 4.2.2 GA you see Ring-0 traps in FXWRAP.SYS, at least occasionally
3) if you use FXWRAP.SYS 17/11/2018 the firewall DOES work ok (that is: you can run various protocols: http, ftp, pop3) IF you turn ON "dynamic firewall feature" AND IF you do NOT include "url_filter.cnf" and "spam.cnf"

Is this correct ? If yes, the error cannot be in FXWRAP.SYS but it must be in either GATEWAY.EXE or in the components that it loads.

**Comment by ecomstation** [comment]
1) no:  on my server 2 i'm using this:     17/11/18 10:55        144.036    124 a---  fxwrap.sys
2) yes, but only on my server2 and not occasionally at every boot
3) yes, exactly

**Comment by lerdmann** [comment]
1. I was talking about GATEWAY.EXE and not about FXWRAP.SYS. I repeat: you are using the 4.2.2 GA version of GATEWAY.EXE on all your computers, correct ?

Are you using Cisco equipment (router) in your network ?

**Comment by ecomstation** [comment]
yes gateway.exe 422ga on both servers

yes cisco switch gigabit ethernet and cisco 800 series internet router

**Comment by SilvanScherrer** [comment]
as the initial crash of fxwrap.sys is fixed I close this issue. further problems need a new ticket, as we can't handle several issues in one ticket. and I can assure that the firewall runs like it should on several installations with the latest fxwrap.sys.
