### ISSUE TITLE
Injoy FW 4.2.2 GUI column "Source" in Active connections window: unredeable

### ISSUE THREAD

**Issue by ecomstation** [bitwiseworks/InJoy#63]
Injoy firewall version 4.2.2 GUI (on all platforms eCS+Windows) the source column in 
"Active connections" Window is unredeable, please see screenshot in attachment

this is a very big issue since if you are receiving an heavy DDOS attack you can't read 
the entire FQDN of the incoming source (the attacker)

please, please, please fix this

![Screenshot (885)](https://user-images.githubusercontent.com/2589993/68119104-10e56f80-ff02-11e9-94bb-a02e3a8c4b25.png)

**Comment by SilvanScherrer** [comment]
in my opinion the only real solution to that would be to add a new column with the IP-Address of the source. As exchanging the source with IP only is not really what I like.

**Comment by ecomstation** [comment]
Il 22/11/2019 14:43, Silvan Scherrer ha scritto:
>
> in my opinion the only real solution to that would be to add a new column with the IP-Address 
> of the source. As exchanging the source with IP only is not really what I like.
>

yes, also having a column with the IP next to the "Source" column in the "Active connections" 
panels will be very very very useful
(of course it's important to keep also the actual classi "Source" with the mnemonic/fqdn)

thanks

-- 
Massimo Sangriso
Consulenza informatica software internet e hardware
http://www.ecomstation.it/
Skype: Massimo Sangriso
pec: massimo.sangriso@legalmail.it

E' compito del ricevente registrare e conservare la documentazione come richiesto dalla legge.

Si prega di inviare le Certificazioni Uniche esclusivamente a mezzo PEC.

Prima di stampare questo e-mail pensa se e' veramente necessario, ci sono sempre meno alberi.
Please consider the environment before printing this e-mail.

Le informazioni contenute in questo messaggio di posta elettronica sono riservate e confidenziali e ne è vietata la diffusione in qualunque modo eseguita.
Qualora Lei non fosse la persona a cui il presente messaggio è destinato La invitiamo ad eliminarlo e a non leggerlo, dandocene gentilmente comunicazione.

The information contained in this e-mail and any attachments are confidential and may also be privileged. If you are not named recipient, please notify the sender immediately and do not disclose the contents to another person, use it for any purpose, or store or copy the information in any medium.
