### ISSUE TITLE
severe issue with download datarates running Injoy FW 4.2.2 with 100Megabit/sec (D/L) fttc connection

### ISSUE THREAD

**Issue by ecomstation** [bitwiseworks/InJoy#66]
Hi all,

if i download a file from (e.g.) this website:  https://www.ubuntu-it.org/download
( but also from others e.g. MS   https://www.microsoft.com/it-IT/download/details.aspx?id=42335  )
on my laptop in my office lan with my Cisco router set as gateway i get about 6,9MegaBytes/sec 

if i download the same file on the same laptop from the same site (or even from MS websites or others) but using my server (configuration: Intel Xeon 4 cores 2,4Ghz, 4GB ram, eCS 2.1 (on bare metal, no VM, with latest AN nov2018 drivers pack and Injoy FW 4.2.2 (3/2019 fxwrap.sys or even original 2014 fxwrap.sys) set as gateway i get downloads of *no more* than 2,5MegaBytes/sec

if i open the FW gui console i see 1-3MegaBytes/sec as *max* download datarate

this is my ip stack configuration:

#Inetcfg:	CURRENT	DEFAULT	MINIMUM	MAXIMUM

keepalive	60	7800	0	7800	KeepAlive (sec)
tcpswinsize	246180	32768	1024	246723	TCP SendWindow Size
tcprwinsize	246180	32768	1024	246723	TCP RecvWindow Size
udpswinsize	246180	9216	1024	246723	UDP SendWindow Size
udprwinsize	246180	41600	1024	246723	UDP RecvWindow Size
lingertime	60	120	0	65535	Linger Time (sec)
probecnt	8	8	1	8	Number Of KeepAlive Probes
ipforward	1	0	0	1	IP Forwarding flag ON/OFF
mtudiscover	1	1	0	1	TCP Path MTU Discovery ON/OFF
arpkillc	300	1200	180	15300	ARP Complete TimeOut (sec)
arpkilli	180	180	60	1200	ARP InComplete TimeOut (sec)
lipcstswinsize	10240	10240	1024	246723	LIPC Stream SendWindow Size
lipcstrwinsize	10240	10240	1024	246723	LIPC Stream RecvWindow Size
lipcdgswinsize	2048	2048	1024	246723	LIPC Dgram SendWindow Size
lipcdgrwinsize	4096	4096	1024	246723	LIPC Dgram RecvWindow Size
synattack	0	0	0	1	SYN Attack Flag ON/OFF
syncookie	0	0	0	1	SYN Cookie Flag ON/OFF
firewall	0	0	0	1	FIREWALL ON/OFF
multidefrt	1	1	0	1	Multiple Default Routes ON/OFF
winscale	1	1	0	1	TCP Window Scale ON/OFF
timestmp	0	0	0	1	TCP TimeStamps ON/OFF
realslow	20	20	1	100	TCP TW Q Slow Timeout ticks
perfhttp	1	1	0	1	Fast Path HTTP ON/OFF
tcpttl		64	64	1	255	TCP  TTL (hops)
udpttl		64	64	1	255	UDP  TTL (hops)
icmpttl		64	64	1	255	ICMP TTL (hops)
fragttl		60	60	1	255	Fragment TTL (sec)
reusetw		1	1	0	1	Reuse Time Wait ON/OFF
msl		30	30	1	16384	TCP MaxSegLifeTime (sec)
cc		0	0	0	1	TTCP function ON/OFF
sack		0	0	0	1	Selective ACK ON/OFF

i've the same situation with all the firewall on my customers setups 
could you help?

thanks

best regards

massimo s.

**Comment by ecomstation** [comment]
i still have this issue also at customers firewalls
50Megabit/sec full granted business contract internet connection with 8 static IPs 
and the firewall do not download more that 2MegaBytes/sec of download
2MegaBytes/sec means a 16Megabit/sec downstreaming connection, this is not true
server is an HP Proliant ML110 with Pentium D dual core running at 3,4Ghz, 
OS is eCS2.2b and it uses acpi 

please could you help?

my Client is complaining and i don't like to run into troubles

**Comment by SilvanScherrer** [comment]
if still an issue with 4.2.3, we might look at it again. but most probably we cant do more, as the architecture gets to its edge.

**Comment by ecomstation** [comment]
yes, i've the same issue also on the 4.2.3 i bought last month
(the issue is with the 4.2.2 and also with 4.2.3 on the same VM)
the VM has 6 cores and run on SSD raid so it should be quite fast..

this is the inetcfg.ini

#Inetcfg:	CURRENT	DEFAULT	MINIMUM	MAXIMUM

keepalive	30	7800	0	7800	KeepAlive (sec)
tcpswinsize	64240	32768	1024	246723	TCP SendWindow Size
tcprwinsize	64240	32768	1024	246723	TCP RecvWindow Size
udpswinsize	9216	9216	1024	246723	UDP SendWindow Size
udprwinsize	41600	41600	1024	246723	UDP RecvWindow Size
lingertime	120	120	0	65535	Linger Time (sec)
probecnt	8	8	1	8	Number Of KeepAlive Probes
ipforward	1	0	0	1	IP Forwarding flag ON/OFF
mtudiscover	0	1	0	1	TCP Path MTU Discovery ON/OFF
arpkillc	1200	1200	180	15300	ARP Complete TimeOut (sec)
arpkilli	180	180	60	1200	ARP InComplete TimeOut (sec)
lipcstswinsize	10240	10240	1024	246723	LIPC Stream SendWindow Size
lipcstrwinsize	10240	10240	1024	246723	LIPC Stream RecvWindow Size
lipcdgswinsize	2048	2048	1024	246723	LIPC Dgram SendWindow Size
lipcdgrwinsize	4096	4096	1024	246723	LIPC Dgram RecvWindow Size
synattack	1	0	0	1	SYN Attack Flag ON/OFF
syncookie	0	0	0	1	SYN Cookie Flag ON/OFF
firewall	0	0	0	1	FIREWALL ON/OFF
multidefrt	0	1	0	1	Multiple Default Routes ON/OFF
winscale	1	1	0	1	TCP Window Scale ON/OFF
timestmp	1	0	0	1	TCP TimeStamps ON/OFF
realslow	20	20	1	100	TCP TW Q Slow Timeout ticks
perfhttp	1	1	0	1	Fast Path HTTP ON/OFF
tcpttl		64	64	1	255	TCP  TTL (hops)
udpttl		64	64	1	255	UDP  TTL (hops)
icmpttl		64	64	1	255	ICMP TTL (hops)
fragttl		60	60	1	255	Fragment TTL (sec)
reusetw		0	1	0	1	Reuse Time Wait ON/OFF
msl		30	30	1	16384	TCP MaxSegLifeTime (sec)
cc		0	0	0	1	TTCP function ON/OFF
sack		0	0	0	1	Selective ACK ON/OFF
