### ISSUE TITLE
Bug with "Load Graphs" function in FW properties (v 4.2.2)

### ISSUE THREAD

**Issue by ecomstation** [bitwiseworks/InJoy#67]
1) You can't type a specific value, the fw GUI will clear automaticall what you wrote

2) So you have to use cursors, but if you have a connection at 100Megabit/sec (eg. fttc) you can't put higher value than 64Megabit/sec that's "8048"as value in the LInk Speed field (that use KiloBytes)

(8048 Kilobytes are 64Megabit)

why this happens?

is 64Megabit/sec the maximum datarate that Injoy 4.2.2 can handle?
or it's just a bug in the UI?

why i can't digit a specific value in the fields?

**Comment by SilvanScherrer** [comment]
this is just a UI issue, which is fixed since long in the tree. But we didn't create a new version just because of that.
