### ISSUE TITLE
fw 4.2.2 crash

### ISSUE THREAD

**Issue by ecomstation** [bitwiseworks/InJoy#68]
this is a follow up of ticket #49 (closed)

from march 2020 i have again this customer so i can follow again the ticket

in attachment 2 exceptq dumps (one occured the at 14th jen 2020 and one at 17th feb 2020)

[injoy_traps.zip](https://github.com/bitwiseworks/InJoy/files/4375178/injoy_traps.zip)

**Comment by SilvanScherrer** [comment]
did you install the latest version Yuri sent you? does this still crash in ipsec sometimes?

**Comment by ecomstation** [comment]
on that server i had a december 2017 injoy fw debug build installed
since i had a number of issues with that 
on 23th may i've reverted back to the original 4.2.2 
but of course i'm running the latest fxwrap.sys driver
build: "bitwise works GmbH:4.2#@##1## 14 Dec 2018 21:06:18"

at the moment i've no crash on IPSEC, i will keep you updated

note: this production firewall server is about 40KM far from my office so each time i've to update something i've to go to the customer's place and this is an issue

**Comment by SilvanScherrer** [comment]
without the latest debug build we can't do anything I'm sorry. as only with this one we would see what might go wrong

**Comment by ecomstation** [comment]
in the last period the internet connection at the customer's place have been upgraded from 6Megabit/sec to 50Megabit/sec, i don't see anymore crashes in the ipsec since then

but don't mind next time i will be at the customer's place i will install the new debug build

i'm also preparing a new firewall machine (this one is an HP proliant ml 110 g5 with intel pentium D 3,4Ghz dual core CPU) and it to do only 2MB/sec (so 16Megabit/sec) downloads

the new machine will be an HP wkstation Intel CoreI7 with more modern hardware so i want to see
if the new machine will have right download datarates

**Comment by SilvanScherrer** [comment]
no more comment since long. so closing the issue
