### ISSUE TITLE
Injoy 4.2.2 + fxwrap.sys 14 dec 2018 build give random issues at server boot

### ISSUE THREAD

**Issue by ecomstation** [bitwiseworks/InJoy#69]
hi all,

Injoy FW 4.2.2 (with 14 dec 2018 fxwrap.sys) randomly don't work at server boot
the server do a scheduled reboot each morning, sometimes the firewall don't work at boot

about "don't work" i mean, no communications at all, no ping, no access to the remote console
the inside lan completely without internet access

OS: eCS 2.2b
hw:  HP proliant ML with Intel Pentium D 3,4Ghz dual core, 3GB ram, SSD storage

Injoy also runs IPSEC and has 2 VPN tunnels 

other stuff:  MSS-Adjust: 1200
Priority: 88

protocol.ini:

[PROT_MAN]

   DRIVERNAME = PROTMAN$

[IBMLXCFG]

   tcpip_nif = tcpip.nif
   FXWRAP_nif = fxwrap.nif
   E100BEO2_nif = E100BEO2.nif
   B57_nif = B57.nif

[tcpip_nif]

   DriverName = TCPIP$
   Bindings   = FXWRAP_nif,B57_nif

[E100BEO2_nif]

   DriverName = E100B$
   SPEED = 0
   FORCEDUPLEX = 0
   TRANSMITBUFFERS = 20
   RECEIVEBUFFERS = 20

[B57_nif]

   DriverName = B57$

[FXWRAP_nif]

   Drivername = FXWRAP1$
   Bindings   = E100BEO2_nif

inetcfg -get all:

#Inetcfg:	CURRENT	DEFAULT	MINIMUM	MAXIMUM

keepalive	60	7800	0	7800	KeepAlive (sec)
tcpswinsize	246723	32768	1024	246723	TCP SendWindow Size
tcprwinsize	246723	32768	1024	246723	TCP RecvWindow Size
udpswinsize	246723	9216	1024	246723	UDP SendWindow Size
udprwinsize	246723	41600	1024	246723	UDP RecvWindow Size
lingertime	60	120	0	65535	Linger Time (sec)
probecnt	8	8	1	8	Number Of KeepAlive Probes
ipforward	1	0	0	1	IP Forwarding flag ON/OFF
mtudiscover	1	1	0	1	TCP Path MTU Discovery ON/OFF
arpkillc	1200	1200	180	15300	ARP Complete TimeOut (sec)
arpkilli	180	180	60	1200	ARP InComplete TimeOut (sec)
lipcstswinsize	10240	10240	1024	246723	LIPC Stream SendWindow Size
lipcstrwinsize	10240	10240	1024	246723	LIPC Stream RecvWindow Size
lipcdgswinsize	2048	2048	1024	246723	LIPC Dgram SendWindow Size
lipcdgrwinsize	4096	4096	1024	246723	LIPC Dgram RecvWindow Size
synattack	0	0	0	1	SYN Attack Flag ON/OFF
syncookie	0	0	0	1	SYN Cookie Flag ON/OFF
firewall	0	0	0	1	FIREWALL ON/OFF
multidefrt	0	1	0	1	Multiple Default Routes ON/OFF
winscale	1	1	0	1	TCP Window Scale ON/OFF
timestmp	1	0	0	1	TCP TimeStamps ON/OFF
realslow	20	20	1	100	TCP TW Q Slow Timeout ticks
perfhttp	1	1	0	1	Fast Path HTTP ON/OFF
tcpttl		64	64	1	255	TCP  TTL (hops)
udpttl		64	64	1	255	UDP  TTL (hops)
icmpttl		64	64	1	255	ICMP TTL (hops)
fragttl		60	60	1	255	Fragment TTL (sec)
reusetw		0	1	0	1	Reuse Time Wait ON/OFF
msl		30	30	1	16384	TCP MaxSegLifeTime (sec)
cc		0	0	0	1	TTCP function ON/OFF
sack		0	0	0	1	Selective ACK ON/OFF

config.sys:

PSD=ACPI.PSD

BASEDEV=BOOTDLY.SYS

REM [ Device Drivers ]
DEVICE=C:\OS2\BOOT\UNICODE.SYS
IFS=C:\OS2\JFS.IFS /LW:5,20,4 /AUTOCHECK:*
	rem IFS=C:\OS2\HPFS.IFS /CACHE:2048 /CRECL:4 /AUTOCHECK:*
 rem IFS=C:\ECS\BOOT\FAT32.IFS /CACHE:2048 /H /Q /EAS
IFS=C:\OS2\BOOT\UDF.IFS /Q
IFS=C:\OS2\BOOT\CDFS.IFS /Q /W
DEVICE=C:\OS2\BOOT\OS2CDROM.DMD /Q
REM DEVICE=C:\OS2\MDOS\VCDROM.SYS
DEVICE=C:\IBMCOM\LANMSGDD.OS2 /I:C:\IBMCOM /S 
DEVICE=C:\IBMCOM\PROTMAN.OS2 /I:C:\IBMCOM
REM DEVICE=C:\OS2\BOOT\TESTCFG.SYS
 rem DEVICE=C:\OS2\BOOT\TESTCFG2.SYS
DEVICE=C:\OS2\BOOT\DOS.SYS
DEVICE=C:\OS2\BOOT\PMDD.SYS
REM DEVICE=C:\OS2\MDOS\VEMM.SYS
REM DEVICE=C:\OS2\MDOS\VXMS.SYS /UMB
REM DEVICE=C:\OS2\MDOS\VDPMI.SYS
REM DEVICE=C:\OS2\MDOS\VDPX.SYS
DEVICE=C:\ECS\SYSTEM\AMouse\AMOUSE.SYS SMP
DEVICE=C:\ECS\SYSTEM\AMouse\USBMOUSE.SYS
 rem DEVICE=C:\OS2\MDOS\VMOUSE.SYS
DEVICE=C:\OS2\BOOT\POINTDD.SYS
DEVICE=C:\OS2\BOOT\USBKBD.SYS
REM DEVICE=C:\OS2\BOOT\USBCOM.SYS
REM DEVICE=C:\TCPIP\bin\vdostcp.sys
REM DEVICE=C:\MMOS2\ssmdd.sys /S:64 /P:64 /H:256 /Q:1024 /E:1024
REM DEVICE=C:\MMOS2\r0stub.sys
REM DEVICE=C:\MMOS2\MMPLAYER\midi.sys
REM DEVICE=C:\MMOS2\vcshdd.sys
DEVICE=C:\ecs\boot\USBRESMG.SYS
REM [ Base Device Drivers ]
 rem BASEDEV=APM.ADD
BASEDEV=IBMKBD.SYS
 rem BASEDEV=TIMER0.SYS
REM BASEDEV=PRINT01.SYS
BASEDEV=CHKDSK.SYS
BASEDEV=USBUHCD.SYS
BASEDEV=USBUHCD.SYS
BASEDEV=USBUHCD.SYS
BASEDEV=USBUHCD.SYS
BASEDEV=USBD.SYS
BASEDEV=USBHID.SYS
 rem BASEDEV=CADH.SYS
BASEDEV=DANIS506.ADD /!BIOS
REM BASEDEV=IBM1FLPY.ADD
REM  BASEDEV=IBM2FLPY.ADD
BASEDEV=USBMSD.ADD /REMOVABLES:8 /FLOPPIES:1
BASEDEV=DANIATAP.FLT
BASEDEV=OS2DASD.DMD
BASEDEV=OS2LVM.DMD
REM [ Paths ]
LIBPATH=.;C:\ECS\DLL;C:\EMX\DLL;C:\OS2\DLL;C:\MPTN\DLL;C:\IBMCOM\DLL;C:\TCPIP\DLL;C:\IBMGSK50\LIB;C:\IBMGSK40\LIB;C:\IBMGSK\LIB;C:\OS2\MDOS;C:\;C:\OS2\APPS\DLL;C:\ECS\SYSTEM\AMOUSE;C:\MMOS2\DLL;C:\MMOS2\FREEDB;C:\PROGRAMS\OPENSSH;c:\util\lib;
SET PATH=C:\MPTN\BIN;C:\IBMCOM;C:\ECS\BIN;C:\TCPIP\BIN;C:\EMX\BIN;C:\IBMGSK50\BIN;C:\IBMGSK40\BIN;C:\IBMGSK\BIN;C:\OS2;C:\OS2\SYSTEM;C:\OS2\INSTALL;C:\;C:\OS2\MDOS;C:\OS2\APPS;C:\ECS\KLIBC\BIN;C:\PROGRAMS\JAVA142\BIN;C:\MMOS2\FREEDB;C:\MMOS2;C:\MMOS2\MMPLAYER;C:\PROGRAMS\OPENSSH;c:\util\fc;
REM SET PATH=C:\MPTN\BIN;C:\IBMCOM;C:\TCPIP\BIN;C:\ECS\BIN;C:\EMX\BIN;C:\IBMGSK50\BIN;C:\IBMGSK40\BIN;C:\IBMGSK\BIN;C:\OS2;C:\OS2\SYSTEM;C:\OS2\INSTALL;C:\;C:\OS2\MDOS;C:\OS2\APPS;C:\ECS\KLIBC\BIN;C:\PROGRAMS\JAVA142\BIN;C:\MMOS2\FREEDB;C:\MMOS2;C:\MMOS2\MMPLAYER;C:\PROGRAMS\OPENSSH;c:\util\fc;
SET DPATH=C:\MPTN;C:\IBMCOM;C:\ECS\LANG;C:\IBMCOM\MACS;C:\OS2;C:\OS2\SYSTEM;C:\OS2\INSTALL;C:\;C:\OS2\BITMAP;C:\OS2\MDOS;C:\OS2\APPS;C:\MMOS2;C:\MMOS2\INSTALL;
SET HELP=C:\MPTN;C:\MPTN\HELP;C:\ecs\help;C:\OS2\HELP;C:\ecs\system\ewps\help;C:\ECS\SYSTEM\AMouse;C:\TCPIP\HELP;C:\MMOS2\HELP;
SET ULSPATH=C:\LANGUAGE
SET BOOKSHELF=C:\OS2\BOOK;C:\ecs\book;C:\EMX\BOOK;C:\TCPIP\HELP;C:\MMOS2;
SET EPMPATH=C:\OS2\APPS;
SET NLSPATH=C:\MPTN\MSG\NLS\%N;C:\TCPIP\msg\ENUS850\%N;
SET MOZ_PLUGIN_PATH=C:\PROGRAMS\MOZ_PLUG
SET LIBC_HOOK_DLLS=C:\OS2\DLL\klibccfg.dll@_kLIBCInitPath!pathrewrite
SET DMIPATH=C:\DMISL\BIN
SET CLASSPATH=C:\os2\javaapps\lvmgui.zip;C:\TCPIP\java;
SET DSPPATH=C:\MMOS2\DSP;
REM [ Device Information ]
DEVINFO=KBD,IT141,C:\OS2\KEYBOARD.DCP
REM [ Kernel Directives ]
AUTOFAIL=YES
BREAK=OFF
BUFFERS=90
CLOCKSCALE=4
CODEPAGE=850,437
COUNTRY=039,C:\OS2\SYSTEM\COUNTRY.SYS
DISKCACHE=1024,LW,32
DOS=LOW,NOUMB
EARLYMEMINIT=TRUE
FCBS=16,8
FILES=64
IOPL=YES
MAXWAIT=1
MEMMAN=SWAP,PROTECT
PRINTMONBUFSIZE=134,134,134
PRIORITY_DISK_IO=YES
PROTECTONLY=NO
PROTSHELL=C:\OS2\PMSHELL.EXE
RESERVEDRIVELETTER=R
RMSIZE=640
SHELL=C:\OS2\MDOS\COMMAND.COM C:\OS2\MDOS
SUPPRESSPOPUPS=C
SWAPPATH=C:\OS2\SYSTEM 256000 256000
THREADS=1024
VIRTUALADDRESSLIMIT=1536
REM [ Environment Variables ]
SET AUTOSTART=PROGRAMS,TASKLIST,FOLDERS
SET COMSPEC=C:\OS2\CMD.EXE
REM SET DELDIR=C:\DELETE,512;D:\DELETE,512;E:\DELETE,512;S:\DELETE,512;T:\DELETE,512;Z:\DELETE,512;
SET DEVICEFONTDISABLED=NO
SET DIRCMD=/V
SET DISPLAYTYPE=VGA
SET ENH_STRETCH=NO
SET ETC=C:\MPTN\ETC
SET GLOSSARY=C:\OS2\HELP\GLOSS;
SET HOME=C:\HOME\DEFAULT
SET HOSTNAME=firewall
SET IKEYMAN40_HOME=C:\IBMGSK40
SET IKEYMAN50_HOME=C:\IBMGSK50
SET IKEYMAN_HOME=C:\IBMGSK
SET IPF_KEYS=SBCS
SET JAVA_HIGH_MEMORY=1
SET JAVA_HOME=C:\PROGRAMS\JAVA142
SET KEYS=ON
SET LANG=it_IT_EURO
SET LOGFILES=C:\var\log
SET MMBASE=C:\MMOS2;
SET MMSTREAM=/S:64 /P:64 /H:256 /Q:1024 /E:1024
SET MMYIELD=10
SET MOZILLA_HOME=C:\HOME\DEFAULT
SET NCDEBUG=4000
SET NOLARGENTEXEICON=1
SET NSPR_OS2_NO_HIRES_TIMER=1
SET OS2_SHELL=C:\OS2\CMD.EXE
SET OS=ecs
SET OSDIR=C:\ecs
SET PROGRAMS=C:\PROGRAMS
SET PROMPT=[$p]
SET RESTARTOBJECTS=STARTUPFOLDERSONLY,REBOOTONLY
SET RUNWORKPLACE=C:\OS2\PMSHELL.EXE
SET SCCANBENUKED=ON
SET SCKILLFEATUREENABLED=ON
SET SHELLHANDLESINC=20
SET SOMDDIR=C:\OS2\ETC\DSOM
SET SOMIR=C:\OS2\ETC\SOM.IR;C:\OS2\ETC\WPSH.IR;C:\OS2\ETC\WPDSERV.IR;C:\OS2\ETC\REXX.IR;
SET SYSTEM_INI=C:\OS2\OS2SYS.INI
SET TCPLANG=en_US
SET TZ=CET-1CES,3,-1,0,7200,10,-1,0,10800,3600
SET UNZIPOPT=-C
SET USER=ECS_USER
SET USER_INI=C:\OS2\OS2.INI
SET USE_HOSTS_FIRST=1
REM [ Executables ]
 rem CALL=C:\ECS\BIN\CACHEF32.EXE /S /F
RUN=C:\OS2\SYSTEM\LVMALERT.EXE
RUN=C:\OS2\EXTENDFS.EXE *
RUN=C:\ECS\SYSTEM\GENMAC\DRIVER\HELPERW.EXE
CALL=C:\IBMCOM\PROTOCOL\NETBIND.EXE
RUN=C:\IBMCOM\LANMSGEX.EXE
REM RUN=C:\OS2\SMSTART.EXE
REM RUN=C:\MPTN\BIN\VDOSCTL.EXE
REM RUN=C:\MMOS2\mmfix.exe
REM RUN=C:\MMOS2\mididmon.exe
REM RUN=C:\MMOS2\mmhelpdd.exe
REM RUN=C:\MMOS2\qrymmcd.exe
REM [ Remarks ]
REM -> TESTCFG2.SYS has been patched to support ACPI
REM [ Temporary Directories ]
SET TMP=C:\var\temp
SET TEMP=C:\var\temp
SET TMPDIR=C:\var\temp
RUN=C:\OS2\ACPIDAEMON.EXE

PAUSEONERROR=NO
REIPL=YES

DEVINFO=SCR,VGA,C:\OS2\BOOT\VIOTBL.DCP
SET VIDEO_DEVICES=VIO_SVGA
SET VIO_SVGA=DEVICE(BVHVGA,BVHSVGA)
DEVICE=C:\OS2\MDOS\VSVGA.SYS
SET GRADD_CHAINS=C1
DEVICE=C:\OS2\GRADD.SYS
DEVICE=C:\OS2\MDOS\VMANWIN.SYS
SET C1=VBE2GRAD
SET GREEXT=PANOGREX

DEVICE=C:\MPTN\PROTOCOL\SOCKETSK.SYS
 rem DEVICE=C:\MPTN\PROTOCOL\SOCKETSK.SYS /GDT:256 /MEM:4096
DEVICE=C:\MPTN\PROTOCOL\AFOS2.SYS
DEVICE=C:\MPTN\PROTOCOL\AFINETK.SYS

RUN=C:\MPTN\BIN\CNTRL.EXE
 rem RUN=C:\MPTN\BIN\CNTRL.EXE /SM 1024 /LM 720

CALL=C:\OS2\CMD.EXE /Q /C C:\MPTN\BIN\MPTSTART.CMD >NUL

DEVICE=C:\IBMCOM\MACS\E100B.OS2
DEVICE=C:\IBMCOM\PROTOCOL\FXWRAP.SYS

DEVICE=C:\IBMCOM\MACS\B57.OS2

**Comment by ydario** [comment]
Since FXWRAP is not loaded in blocking mode, even without gateway running the interfaces are not blocked. So something else is flooding the stack or keeping the machine busy.

**Comment by ecomstation** [comment]
when injoy firewall get started by startup.cmd the machine stop communicating at all on the tcp/ip
so the issue is of course generated by the firewall application

which kind of analysis have been done to write this?

how can i verify why injoy firewall is malfunctioning if it writes no errors in the logs?

**Comment by ydario** [comment]
'not working at boot' and 'firewall get started by startup.cmd' are not the same thing.

Also a timed rexx script is involved in injoy firewall startup and everything was working until about one month ago.

Could you provide logs with connectivity testing before and after ijfw starting? Also ijfw startup logs are required.

**Comment by ecomstation** [comment]
i've finally updated the rexx procedure to store Injoy logs (the ones under \injoy\logs dir)
so i can give more details if it happens again

yesterday evening i've lowered the the priority from 88 to 78 and at the scheduled reboot
it started with no issues (the INJOY GUI show docs that say that too high priority could give system instability)

a question, i don't use genmac drivers
RUN=C:\ECS\SYSTEM\GENMAC\DRIVER\HELPERW.EXE
this line could create issues to the stack ip or to Injoy FW?

another question which kind of connectivity logs do you need?
a ping log? some netstat output? iptrace?

thanks

massimo

**Comment by ydario** [comment]
I think helperw is only for genmac drivers, so it could be safely removed.

Regarding connectivity logs, pinging of local lan interface, router interface and some name resolution should show networking jobs.

**Comment by ecomstation** [comment]
today injoy firewall did it again, it stopped working closing any communication at the server boot in the early morning

i'm completely sure that's a gateway issue since i've put a 1 minute delay in the startup.cmd and after i start injoy firewall
i've normal logs until injoy start 
logs end there, when gateway starts

i suspect that i've some old Klibc DLLs this is the list that may cause issues:

17/04/11 21:56 53.211 0 a--- liba52.dll
13/03/05 13:44 204.950 0 a--- libc01.dll
13/03/05 13:44 230.785 0 a--- libc04.dll
17/04/11 21:56 356.330 0 a--- libc05.dll
26/10/14 20:17 48.179 124 a--- libc06.dll
26/10/14 20:17 48.179 124 a--- libc061.dll
26/10/14 20:17 157.161 124 a--- libc062.dll
26/10/14 20:17 157.161 124 a--- libc063.dll
26/10/14 20:17 157.213 124 a--- libc064.dll
26/10/14 20:17 157.213 124 a--- libc065.dll
21/08/17 23:00 1.361.663 124 a--- libc066.dll
13/03/05 13:44 562.710 0 a--- libc06b4.dll
14/04/20 9:27 1.158.672 0 a--- libcn0.dll
29/08/17 17:45 34.579 124 a--- libcx0.dll

27/06/17 13:30 26.491 0 a--- gcc1.dll
13/03/05 13:44 25.714 0 a--- gcc321m.dll
13/03/05 13:45 24.270 0 a--- gcc321s.dll
13/03/05 13:44 25.665 0 a--- gcc322.dll
13/03/05 13:45 14.350 0 a--- gcc322m.dll
26/10/14 20:12 32.801 0 a--- gcc335.dll
2/02/15 10:38 3.178 124 a--- gcc434.dll
2/02/15 10:38 3.178 124 a--- gcc444.dll
2/02/15 10:38 3.912 124 a--- gcc446.dll
2/02/15 10:38 3.912 124 a--- gcc452.dll
2/02/15 10:38 4.122 124 a--- gcc473.dll
2/02/15 10:38 4.210 124 a--- gcc492.dll

please could you help and suggest me the correct DLL version ones?

thanks

massimo

**Comment by SilvanScherrer** [comment]
you have a big problem with klibc. why don't you just use rpm to install it. as right njow you have 2 complete libc on your system. and this might or might not run. libcx as package brings forwarder to all libc versions. and you have old libcx with new libcn. which works ok, but also libcx got a lot changes fixes. I really would use yum to update your system. We can for sure help you in updating your system right, but this can't be for free, as it has nothing to do with injoy.

**Comment by ecomstation** [comment]
all the KLIBC dlls in the ecs\dll path have been removed 
all the KLIBC dlls are under \util\lib and i keep them updated manually
so you can just copy and paste here the URLS to download the right zip packages on the netlabs repositories if this is a requirement of your software

i tried to install anpm on the firewall machine and it don't work, so this is not reliable for me
i will keep on updating manually

you should update the readme.txt of your software with the urls to the required libraries

thanks

regards

massimo

**Comment by SilvanScherrer** [comment]
as it' seems you dislike all our recommendations it will be hard to help. latest libc/libcx is always at http://rpm.netlabs.org/release/00/zip/

**Comment by ecomstation** [comment]
give me time, when the machine will be stable, i will install yum

at the moment the machine is not stable, so i'm afraid to worse the situation
