### ISSUE TITLE
Injoy 4.2.2 + fxwrap.sys 14 dec 2018 build loss in performances have to schedule a daily reboot of the server

### ISSUE THREAD

**Issue by ecomstation** [bitwiseworks/InJoy#70]
hi all,

Injoy FW 4.2.2 (with 14 dec 2018 fxwrap.sys) loses a lot in performances after days of uptime
in the last years i had a scheduled reboot each night to keep performances good
since sometimes when startup.cmd start the gateway process it happens that the server don't answer anymore to any kind of connection (ticket closed by Yuri Dario, dunno why... number 69)
so to reduce this issue i've removed the daily reboot from the cron, what happens that with about 2/3 days of uptime the firewall severely loses performance and the server needs to be restarted with setboot /b

OS: eCS 2.2b
hw: HP proliant ML with Intel Pentium D 3,4Ghz dual core, 3GB ram, SSD storage

Injoy also runs IPSEC and has 2 VPN tunnels

so that if i put the daily reboot sometimes i've issues when inioy firewall start so that the connection of the customer is broken (like without internet), if i remove the scheduled reboots after some days of uptime (just 2 or 3) the firewall becomes very slow and i've to connect to the server and manually reboot it with a setboot /b

please help this is a serious trouble for me

**Comment by SilvanScherrer** [comment]
if still an issue with 4.2.3, we might look at it again. but most probably we cant do more, as the architecture gets to its edge.
