### ISSUE TITLE
4.2.2 GA + fxwrap.sys (14 dec 2018)

### ISSUE THREAD

**Issue by ecomstation** [bitwiseworks/InJoy#72]
Syn attacks reach the ftpD (21) port even if the port 21 is closed and firewall running in stealth mode

netstat -s result:

     0 STREAM         ftp..21         ftp..21    23.225.152.7  SYN_RCVED
     0 STREAM         ftp..21         ftp..21   154.91.38.145  SYN_RCVED 

OS eCS 2.1 + nov. 2018 AN driver package
Nic driver:  AN's Intel(R) PRO/1000 Network Driver (MultiMac32-E1000B) for OS/2"  Version    = 1.1.3                        
FW security level: 5
Stealth mode: ON
Dynamic fw features: OFF
Assemble packets: ON
MAX T.U: 1500
MSS Auto Adjust: Disabled
Priority: 50

kLibc:

28/03/20 13:33         45.363    124 a---  libc06.dll                           
28/03/20 13:33         45.364    124 a---  libc061.dll                          
28/03/20 13:33        153.497    124 a---  libc062.dll                          
28/03/20 13:33        153.497    124 a---  libc063.dll                          
28/03/20 13:33        153.563    124 a---  libc064.dll                          
28/03/20 13:33        153.563    124 a---  libc065.dll                          
28/03/20 13:33        316.502    124 a---  libc066.dll                          
28/03/20 13:33      1.216.805    124 a---  libcn0.dll                           
31/03/20 13:24         52.267    124 a---  libcx0.dll                

so that the ftpD (Moylan's ftpD) becomes out of control and must be task-killed

                     
thanks
regards

massimo

**Comment by SilvanScherrer** [comment]
if still an issue with 4.2.3, we might look at it again.
