### ISSUE TITLE
Hyperthreading HW requirements and Injoy firewall (4.2.2) - performances

### ISSUE THREAD

**Issue by ecomstation** [bitwiseworks/InJoy#73]
Hi all,

i've a couple of questions.

On a PC with Intel Corei7 is better to activate the hyperthreading in the bios or not?
ACPI (latest AN driver package) with HT see 8 cores, with HT disabled only 4 cores.

Which is the best setting for Injoy Firewall 4.2.2 (Talking about performances)?

Always talking about performances, it should be really helpful if Bitwiseworks should public a web page
with a table with performances/hardware requirements needed for Injoy Firewall.

i mean something like this:

ADSL 20Megabit/sec    1GBram   1Core CPU at 2Ghz  storage HDD or SSD
FTTC 30-50Megabit/sec   2GBram  4Core CPU at 2Ghz   storage HDD or SSD
FTTC 100Megabit/sec       " "          4Core CPU at 3,4Ghz storage SSD
FTTH 1Gigabit/sec etc. etc.. etc..

thanks
best regards

massimo s.

**Comment by SilvanScherrer** [comment]
as we relly on ArcaOS or eCS and HT was never recommended by them. We don't recommend it either. Why they don't recommend you need to ask them.

**Comment by ecomstation** [comment]
ok, i will keep it disabled
thanks a lot 

about the 2nd question is that possible?
it should be very very helpful
