### ISSUE TITLE
injoy fw 4.2.2 18/6/2020 debug build - fw stopped working after a restart from the remote gui management

### ISSUE THREAD

**Issue by ecomstation** [bitwiseworks/InJoy#75]
eCS 2.2b + latest AN driver package
Injoy FW 4.2.2 debug build 18/06/2020

i disabled the VPN plugin and said ok to restart the firewall from the popup that opens from the remote gui 
and the remote firewall stopped working completely, no more way to access the remote firewall
i had to ask the customer ppl at the office to cold restart the server

let me know if you need further info so to fix this issue asap

thanks
regards

massimo s.

**Comment by ecomstation** [comment]
this issue is still not fixed
even some minutes ago 5 may 2021, i've activated IPSEC plugin and restarted the FW from the gui
i had to reboot the server, since the FW stopped working closing all IP communications

**Comment by SilvanScherrer** [comment]
if still an issue with 4.2.3, we might look at it again.  and when this happens we would need to see all logs bevore something is restarted.
