### ISSUE TITLE
ICMP issue with Injoy FW 4.2.2 GA + fxwrap.sys (14 dec 2018)

### ISSUE THREAD

**Issue by ecomstation** [bitwiseworks/InJoy#77]
I've this strange issue
the internet connection has 8 public static IPs, WAN nic of FW has static/public IP, FW security level 4, IPSEC with tunnel VPN active
the connection is a professional FTTC 100Mbit/sec down 20Mbit/sec up.

PC and servers (and appliances too) inside the lan (they use the injoy FW lan NIC IP as gateway) can't ping any server/IP on the internet.
I can ping everything from the firewall.

I don't have any rule that block ICMP and i've also put on firerule a manual created rule that allows ICMP.

The issue also show if i disable the IPSEC/VPN plugin.

I don't have dynamic firewall features active.

I'm running out of ideas, let me know if you need further info, configurations or such.

thanks

massimo s.

**Comment by SilvanScherrer** [comment]
did you try with only one external IP? As here all runs smooth.
Try to narrow down the issue and start by a standard installation. and see if it works there. then add featue by feature and look where is stops.

**Comment by ecomstation** [comment]
i've also (to try) disabled ipsec/vpn plugin, also i don't use dhcp
but the ICMP   LAN -> internet do not work either

i can try to reinstall the firewall, but this is not a simple solution since i should go to the client's workplace

do you have another suggestion?
do you need more info?
configuration files etc.?

**Comment by SilvanScherrer** [comment]
no need to try it on customer side, just try to reproduce it on your side.

**Comment by ecomstation** [comment]
Is there not a diag tool to run that check the Injoy FW setup as other applications have?
thanks 

What could i reproduce here that are different IP, different configuration etc.

massimo

**Comment by SilvanScherrer** [comment]
give me the output of traceroute to www.google.com from the firewall and from inside the lan. eventually I see something.

**Comment by ecomstation** [comment]
thanks you

sent in private email

**Comment by SilvanScherrer** [comment]
if still an issue with 4.2.3, we might look at it again.

**Comment by ecomstation** [comment]
i've found that upgrading to fxwrap 4.2.2 beta (build 14 Dec 2018 21:06:18) from 4.2.0 fxwrap.sys show the issue 

if i put back fxwrap.sys 4.2.0 ping start again to work
but i'd prefere to keep fxwrap 4.2.2 since afaik it have perfomance improvements
do you have a 4.2.x fixed for the ICMP issue?

thanks

massimo

**Comment by SilvanScherrer** [comment]
did you try with 4.2.3 fxwrap.sys?

**Comment by ecomstation** [comment]
no, since this is a firewall not of mine
i just asked if you'd have a 4.2.2 fixed for the icmp issue

**Comment by ecomstation** [comment]
if i can add some details we have analyzed this issue with my ISP
and the ICMP arrives to the firewall, the firewall nat engine send it to the destination (user PC or device)
but the nat firewall engine don't answer back

this don't happens with 4.2.0 fxwrap.sys driver, but 4.2.2 afaik have perfomance improvements

**Comment by SilvanScherrer** [comment]
the build of fxwrap you use seems not a release build. so we cant help here. you need to try latest, as we only support this build.

**Comment by ecomstation** [comment]
i kindly asked if you have a 4.2.2 updated / or fixed
the answer is yes or not

thanks you
i will let the customer know

**Comment by SilvanScherrer** [comment]
4.2.3 is the only version we support. So no no new 4.2.2 build.

**Comment by ecomstation** [comment]
the issue has been opened and verified in november 2022
and you answer this in september 2024?
with no solution in allmost 2 years?

**Comment by lerdmann** [comment]
to make things clear: fxwrap.sys knows nothing about ICMP, TCP or UDP packets (with the exception for special handling of incoming DHCP packets). It only checks the ethertype of ethernet packets and routes all IPV4 packets to the firewall and everything else is directly passed on to/from the protocol drivers. That said, your ICMP problem cannot be fixed in the driver. If the driver really makes a difference, then you should upgrade to the latest version. I have tested it with a ping to www.microsoft.com and that worked as it should. I have not yet tested the other direction (incoming ping).

**Comment by ecomstation** [comment]
the ping on the firewall server (eCS 2.x) works correctly
it do not work inside the lan
if i put back the 4.2.0 fxwrap driver and i reboot the server where the fw is instaled the ping works again
the ICMP (as settings) on the firewall is completely open
